package:
  name: alsa-lib
  version: 1.2.8
  epoch: 0
  description: Advanced Linux Sound Architecture (ALSA) library
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: LGPL-2.1-or-later
environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - automake
      - autoconf
      - linux-headers
pipeline:
  - uses: fetch
    with:
      expected-sha256: 1ab01b74e33425ca99c2e36c0844fd6888273193bd898240fe8f93accbcbf347
      uri: https://alsa-project.org/files/pub/lib/alsa-lib-${{package.version}}.tar.bz2
  - uses: autoconf/configure
    with:
      opts: |
        --disable-python \
        --disable-static \
        --disable-resmgr \
        --enable-rawmidi \
        --enable-seq \
        --enable-aload \
        --disable-dependency-tracking \
        --without-versioned
  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip
subpackages:
  - name: alsa-lib-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - alsa-lib
