package:
  name: apk-tools
  version: 2.12.10
  epoch: 0
  description: "apk-tools (Wolfi package manager)"
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: GPL-2.0-only
  dependencies:
    runtime:
      - ca-certificates-bundle
environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/bootstrap/stage3
    keyring:
      - https://packages.wolfi.dev/bootstrap/stage3/wolfi-signing.rsa.pub
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - scdoc
      - zlib-dev
      - openssl-dev
      - lua5.3
      - lua5.3-lzlib
      - lua5.3-dev
pipeline:
  - uses: fetch
    with:
      uri: https://gitlab.alpinelinux.org/alpine/apk-tools/-/archive/v${{package.version}}/apk-tools-v${{package.version}}.tar.gz
      expected-sha256: f2d9fe9fb1e02046e1d906e2a55459e6f05b25deb71117ccbe618f124bd14786
  - runs: |
      sed -i -e 's:-Werror::' Make.rules
      echo "FULL_VERSION=${{package.version}}-r${{package.epoch}}" > config.mk
  - runs: |
      make LUA="lua5.3" V=1
  - runs: |
      make LUA="lua5.3" V=1 DESTDIR="${{targets.destdir}}" install

      install -d "${{targets.destdir}}"/var/lib/apk
      install -d "${{targets.destdir}}"/var/cache/misc
      install -d "${{targets.destdir}}"/etc/apk/keys
      install -d "${{targets.destdir}}"/etc/apk/protected_paths.d
  - uses: strip
subpackages:
  - name: "apk-tools-dev"
    description: "headers for libapk"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - apk-tools
  - name: "lua5.3-apk"
    description: "Lua module for libapk"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr
          mv "${{targets.destdir}}"/usr/lib "${{targets.subpkgdir}}"/usr/lib
