package:
  name: argo-workflows
  version: 3.5.10
  epoch: 2
  description: Workflow engine for Kubernetes.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
      - node-gyp
      - nodejs-20
      - openssl
      - python3
      - yarn

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 25829927431d9a0f46d17b72ae74aedb8d700884
      repository: https://github.com/argoproj/argo-workflows
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: github.com/docker/docker@v26.1.5

  - name: clean yarn user global cache
    runs: |
      yarn cache clean

  - uses: patch
    with:
      patches: ui-add-resolution-to-upgrade-to-braces-3.0.3.patch

  - name: yarn bump deps
    runs: |
      # Create checkpoint
      git commit -m "checkpoint for package.json" ui/package.json
      # See https://github.com/yarnpkg/yarn/issues/4986 for options
      # Recalculate/upgrade transitive dependencies to bump ws
      yarn --cwd ui remove jest; yarn --cwd ui add --dev 'jest@^26.6.3'
      yarn --cwd ui remove webpack-dev-server ; yarn --cwd ui add --dev 'webpack-dev-server@^4.15.0'
      # Ensure no dependencies changes
      git --no-pager diff --exit-code -- ui/package.json
      # Revert to ensure expected-commited is used for the build info
      git reset HEAD^

  - runs: |
      # Our global LDFLAGS conflict with a Makefile parameter
      unset LDFLAGS

      make dist/workflow-controller
      make dist/argo
      make dist/argoexec

      mkdir -p ${{targets.destdir}}/usr/bin
      mv dist/argo ${{targets.destdir}}/usr/bin/

  - uses: strip

subpackages:
  - name: "argo-workflows-known-hosts"
    description: "known hosts file for argo workflows"
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/etc/ssh
          cp hack/ssh_known_hosts ${{targets.subpkgdir}}/etc/ssh/
      - uses: strip

  - name: "argo-workflow-controller"
    description: "Argo workflow controller"
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin/
          mv dist/workflow-controller ${{targets.subpkgdir}}/usr/bin/
      - uses: strip

  - name: "argo-workflow-executor"
    description: "Argo workflow executor"
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin/
          mv dist/argoexec ${{targets.subpkgdir}}/usr/bin/
      - uses: strip

  - name: argo-workflow-controller-compat
    pipeline:
      - runs: |
          # Symlink the binary from usr/bin to /
          mkdir -p "${{targets.subpkgdir}}"
          ln -sf /usr/bin/workflow-controller ${{targets.subpkgdir}}/workflow-controller
    dependencies:
      runtime:
        - argo-workflow-controller

  - name: argo-workflow-executor-compat
    pipeline:
      - runs: |
          # Symlink the binary from usr/bin to /
          mkdir -p "${{targets.subpkgdir}}"
          ln -sf /usr/bin/argoexec ${{targets.subpkgdir}}/argoexec
    dependencies:
      runtime:
        - argo-workflow-executor

  - name: argo-workflow-cli
    pipeline:
      - runs: |
          # Symlink the binary from usr/bin to /
          # Argocli serves the server https://github.com/argoproj/argo-workflows/blob/master/Dockerfile#L110
          mkdir -p "${{targets.subpkgdir}}"
          ln -sf /usr/bin/argo ${{targets.subpkgdir}}/argo
    dependencies:
      runtime:
        - argo-workflows

  - name: "argo-workflows-ui"
    description: "Argo workflows embedded UI"
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/lib/argo-workflows-ui
          cp -ar ui/ ${{targets.subpkgdir}}/usr/lib/argo-workflows-ui

update:
  enabled: true
  github:
    identifier: argoproj/argo-workflows
    strip-prefix: v
