package:
  name: asciidoctor
  version: 2.0.21
  epoch: 0
  description: A fast, open source text processor and publishing toolchain, written in Ruby, for converting AsciiDoc content to HTML 5, DocBook 5, and other formats.
  copyright:
    - paths:
        - "*"
      attestation:
      license: MIT
  dependencies:
    runtime:
      - ruby-3.1

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - ruby-3.1
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/asciidoctor/asciidoctor
      tag: v${{package.version}}
      expected-commit: 1ec651ddcf4d2cb49576e7cc62c17ec33f8aa5c1

  - uses: ruby/build
    with:
      gem: ${{package.name}}

  - uses: ruby/install
    with:
      gem: ${{package.name}}
      version: ${{package.version}}

update:
  enabled: true
  github:
    identifier: asciidoctor/asciidoctor
    strip-prefix: v
    use-tag: true
    tag-filter: v2
