package:
  name: botan
  version: 3.3.0
  epoch: 0
  description: "Cryptography Toolkit"
  copyright:
    - license: BSD-2-Clause

environment:
  contents:
    packages:
      - boost-dev
      - build-base
      - busybox
      - bzip2-dev
      - ca-certificates-bundle
      - python3
      - sqlite-dev
      - wolfi-base
      - xz-dev
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/randombit/botan
      expected-commit: 9074b04c1303a24e2084f8325fa570a5ad4f2478
      tag: ${{package.version}}

  - name: Configure and build
    runs: |
      python3 ./configure.py \
        --prefix=/usr \
        --mandir=/usr/share/man \
        --with-bzip2 \
        --with-lzma \
        --with-boost \
        --with-sqlite3 \
        --with-zlib \
        --with-os-feature=getrandom \
        --disable-static

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: botan-dev
    pipeline:
      - uses: split/dev

update:
  enabled: true
  github:
    identifier: randombit/botan
    use-tag: true
