package:
  name: bubblewrap
  version: 0.7.0
  epoch: 0
  description: "Unprivileged sandboxing tool"
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: LGPL-2.0-or-later
  dependencies:
    runtime:
environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - build-base
      - bash
      - meson
      - libcap-dev
pipeline:
  - uses: fetch
    with:
      uri: https://github.com/containers/bubblewrap/archive/refs/tags/v${{package.version}}.tar.gz
      expected-sha256: a336aa1f25bb36b14ba452570d51bbf6b03234f68599015b386031fa8a84ee19
  - runs: |
      meson --prefix=/usr -Drequire_userns=true . output
      meson compile -C output
      DESTDIR="${{targets.destdir}}" meson install --no-rebuild -C output
subpackages:
  - name: bubblewrap-bash-completion
    description: bash completion for bubblewrap
    pipeline:
      - runs: |
          set -x
          mkdir -p "${{targets.subpkgdir}}/usr/share/bash-completion/completions"
          mv "${{targets.destdir}}/usr/share/bash-completion/completions/bwrap" \
            "${{targets.subpkgdir}}/usr/share/bash-completion/completions/bwrap"
          rm -rf "${{targets.destdir}}/usr/share/bash-completion"
    dependencies:
      runtime:
        - bubblewrap
  - name: bubblewrap-zsh-completion
    description: zsh completion for bubblewrap
    pipeline:
      - runs: |
          set -x
          mkdir -p "${{targets.subpkgdir}}/usr/share/zsh/site-functions"
          mv "${{targets.destdir}}/usr/share/zsh/site-functions/_bwrap" \
            "${{targets.subpkgdir}}/usr/share/zsh/site-functions/_bwrap"
          rm -rf "${{targets.destdir}}/usr/share"
    dependencies:
      runtime:
        - bubblewrap
