package:
  name: buildah
  version: 1.37.1
  description: "A tool that facilitates building OCI images"
  epoch: 0
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
      - gpgme-dev
      - libassuan-dev
      - libgpg-error-dev
      - libseccomp-dev
      - libseccomp-static

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/containers/buildah
      tag: v${{package.version}}
      expected-commit: 67cc51e90efae84919a60ca5140f7dccd2ea2959

  - uses: go/bump
    with:
      deps: github.com/opencontainers/runc@v1.2.0-rc.1

  - runs: |
      make
      make install PREFIX=${{targets.destdir}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: containers/buildah
    strip-prefix: v
    tag-filter: v
