package:
  name: bun
  version: 1.0.28
  epoch: 0
  description: "Incredibly fast JavaScript runtime, bundler, test runner, and package manager - all in one"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - autoconf
      - automake
      - bash
      - bun-bootstrap # bun requires itself to build. this can get moved to our real build in the future
      - busybox
      - ccache
      - clang-16
      - clang-16-dev
      - cmake
      - coreutils
      - curl
      - git
      - glibc-iconv
      - go
      - icu-dev
      - libtool
      - llvm-lld-16
      - llvm16
      - m4
      - perl
      - pkgconf
      - pkgconf-dev
      - ruby-3.3
      - rust
      - samurai
      - sed

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/oven-sh/bun
      expected-commit: 7056384702231f634e4e5d0f7c65965041314fc6
      tag: bun-v${{package.version}}

  # bun requires a specific zig to build
  - runs: |
      bun install -g @oven/zig

  - runs: |
      export PATH="$PATH:/$HOME/.bun/bin"
      bun setup
      bun run build:release

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin
      mv ./build-release/bun ${{targets.destdir}}/usr/bin

      # symlink bunx as bun: https://github.com/oven-sh/bun/blob/main/dockerhub/distroless/Dockerfile#L70
      ln -s /usr/bin/bun ${{targets.destdir}}/usr/bin/bunx

  - uses: strip

update:
  enabled: true
  github:
    identifier: oven-sh/bun
    use-tag: true
    strip-prefix: bun-v

test:
  pipeline:
    - runs: |
        bun --version
        touch foo.js
        bunx prettier foo.js
