package:
  name: c-ares
  version: 1.27.0
  epoch: 0
  description: "an asynchronous DNS resolution library"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://c-ares.haxx.se/download/c-ares-${{package.version}}.tar.gz
      expected-sha256: 0a72be66959955c43e2af2fbd03418e82a2bd5464604ec9a62147e37aceb420b

  - uses: autoconf/configure
    with:
      # Enabling tests requires a gmock dependency. We have that packaged, but it introduces a dependency cycle.
      opts: --enable-shared --enable-tests=no

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "c-ares-dev"
    description: "headers for c-ares"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libev

  - name: "c-ares-doc"
    description: "c-ares documentation"
    pipeline:
      - uses: split/manpages

update:
  enabled: true
  release-monitor:
    identifier: 5840
