package:
  name: cassandra-reaper
  version: 3.5.0
  epoch: 0
  description: Automated Repair Awesomeness for Apache Cassandra
  copyright:
    - license: Apache-2.0
  target-architecture:
    - x86_64
  dependencies:
    runtime:
      - bash
      - busybox
      - openjdk-11-jre
      - py3-requests

environment:
  contents:
    packages:
      - build-base
      - maven
      - nvm
      - openjdk-11
      - openjdk-11-default-jvm
      - openssl-dev
      - py3-setuptools
      - python3
      - wolfi-base
  environment:
    JAVA_HOME: /usr/lib/jvm/java-11-openjdk

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/thelastpickle/cassandra-reaper
      tag: ${{package.version}}
      expected-commit: adabd8d627ec741935c1fc6fd6bfb1f81477e460

  - uses: patch
    with:
      patches: upgrade-deps.patch

  # Install native binary JAR to $HOME/.m2 so it can be used later
  - runs: |
      builddir=$(pwd)
      source /usr/share/nvm/nvm.sh
      nvm install v12
      nvm use v12
      MAVEN_OPTS="-Xmx384m" mvn -B install -DskipTests -Drat.excludesFile=rat-exclusions.txt

      mkdir -p "${{targets.destdir}}"//usr/local/bin
      mkdir -p "${{targets.destdir}}"//usr/local/lib
      mkdir -p "${{targets.destdir}}"/etc/cassandra-reaper

      echo "listing files:"
      ls -latr $builddir/src/server/target/
      SHADED_JAR="src/server/target/cassandra-reaper-${{package.version}}.jar"
      echo "Shaded jar: $SHADED_JAR"
      cp -r $builddir/src/server/src/main/docker/cassandra-reaper.yml "${{targets.destdir}}"/etc/cassandra-reaper/cassandra-reaper.yml
      cp -r $builddir/src/server/src/main/docker/shiro.ini "${{targets.destdir}}"/etc/cassandra-reaper/shiro.ini
      cp -r $builddir/src/server/src/main/docker/entrypoint.sh "${{targets.destdir}}"/usr/local/bin/entrypoint.sh
      cp -r $builddir/src/server/src/main/docker/configure-persistence.sh "${{targets.destdir}}"/usr/local/bin/configure-persistence.sh
      cp -r $builddir/src/server/src/main/docker/configure-metrics.sh "${{targets.destdir}}"/usr/local/bin/configure-metrics.sh
      cp -r $builddir/src/server/src/main/docker/configure-webui-authentication.sh "${{targets.destdir}}"/usr/local/bin/configure-webui-authentication.sh
      cp -r $builddir/src/server/src/main/docker/configure-jmx-credentials.sh "${{targets.destdir}}"/usr/local/bin/configure-jmx-credentials.sh
      cp -r $builddir/$SHADED_JAR "${{targets.destdir}}"/usr/local/lib/cassandra-reaper.jar
      cp -r $builddir/src/packaging/bin/spreaper "${{targets.destdir}}"/usr/local/bin/spreaper

      touch "${{targets.destdir}}"/etc/cassandra-reaper/cassandra-reaper.yml
      touch "${{targets.destdir}}"/etc/cassandra-reaper/shiro.ini

      chmod +x \
        "${{targets.destdir}}"/usr/local/bin/entrypoint.sh \
        "${{targets.destdir}}"/usr/local/bin/configure-persistence.sh \
        "${{targets.destdir}}"/usr/local/bin/configure-webui-authentication.sh \
        "${{targets.destdir}}"/usr/local/bin/configure-metrics.sh \
        "${{targets.destdir}}"/usr/local/bin/configure-jmx-credentials.sh \
        "${{targets.destdir}}"/usr/local/bin/spreaper

update:
  enabled: true
  github:
    identifier: thelastpickle/cassandra-reaper
