package:
  name: cbindgen
  version: 0.26.0
  epoch: 0
  description: Tool to generate C bindings from Rust code
  copyright:
    - license: MPL-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - rust

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/mozilla/cbindgen
      tag: v${{package.version}}
      expected-commit: 703b53c06f9fe2dbc0193d67626558cfa84a0f62

  - runs: |
      cargo build --release
      mkdir -p ${{targets.destdir}}/usr/bin
      cp target/release/cbindgen ${{targets.destdir}}/usr/bin/

test:
  environment:
    contents:
      packages:
        - rustup
  pipeline:
    - runs: |
        # We need to install nightly rust because cbindgen uses a nightly
        # feature (-Zunpretty=expanded).
        rustup install nightly
        ARCH=$(uname -m)
        export PATH="$HOME/.rustup/toolchains/nightly-${ARCH}-unknown-linux-gnu/bin:$PATH"
        cbindgen --version
        cbindgen --help
        cbindgen --config cbindgen.toml --crate bitfield --output my_header.h --lang c
        cat my_header.h

update:
  enabled: true
  github:
    identifier: mozilla/cbindgen
    strip-prefix: v
