package:
  name: clusterctl
  version: 1.6.2
  epoch: 0
  description: A command line tool to manage clusters created by cluster API
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-sigs/cluster-api
      tag: v${{package.version}}
      expected-commit: da795db4c7da093866fc5b4c4648f795714bc0c3

  - uses: go/build
    with:
      packages: ./cmd/clusterctl
      repository: https://github.com/kubernetes-sigs/cluster-api
      ldflags: $(hack/version.sh)
      output: clusterctl

  - uses: strip

update:
  enabled: true
  github:
    identifier: kubernetes-sigs/cluster-api
    strip-prefix: v
