package:
  name: conda
  version: 24.1.2
  epoch: 0
  description: "A system-level, binary package and environment manager running on all major operating systems and platforms."
  copyright:
    - license: BSD-3-Clause
  options:
    no-provides: true
    no-depends: true
  dependencies:
    runtime:
      - py3-archspec
      - py3-packaging
      - py3-pluggy
      - py3-requests
      - py3-ruamel-yaml
      - py3-tqdm
      - python3

environment:
  contents:
    packages:
      - bash
      - busybox
      - ca-certificates-bundle
      - py3-charset-normalizer
      - py3-hatch
      - py3-hatchling
      - py3-idna
      - py3-pip
      - py3-requests
      - py3-urllib3
      - py3-wheel
      - py3-zstandard
      - python3
      - wget
      - wolfi-base
  environment:
    # This is needed to work around the error "ValueError: ZIP does not support timestamps before 1980"
    SOURCE_DATE_EPOCH: 315532800

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/conda/conda
      tag: ${{package.version}}
      expected-commit: 69131a4d2231d1d648956beb5b98fe0af40ef9d0

  - runs: |
      pip install conda-package-handling
      hatch build
      python3 -m installer -d "${{targets.destdir}}" dist/conda*.whl

update:
  enabled: true
  github:
    identifier: conda/conda

test:
  pipeline:
    - runs: |
        conda --version
        conda info
