package:
  name: culmus
  version: 0.133
  epoch: 0
  description: A collection of Type1 and TrueType Hebrew fonts
  copyright:
    - license: GPL-2.0-only

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: fetch
    with:
      expected-sha256: c0c6873742d07544f6bacf2ad52eb9cb392974d56427938dc1dfbc8399c64d05
      uri: http://downloads.sourceforge.net/${{package.name}}/${{package.name}}-${{package.version}}.tar.gz

  - runs: |
      ls -latr
      #  # install Type1 fonts
       install -Dm755 -d "${{targets.destdir}}"/usr/share/fonts/Type1
       install -Dm644 ./*.afm \
            "${{targets.destdir}}"/usr/share/fonts/Type1
      install -Dm644 ./*.pfa \
            "${{targets.destdir}}"/usr/share/fonts/Type1
       # install ttf fonts
       install -Dm755 -d "${{targets.destdir}}"/usr/share/fonts/TTF
       install -Dm644 ./*.ttf \
         "${{targets.destdir}}"/usr/share/fonts/TTF
       # install otf fonts
       install -Dm755 -d "${{targets.destdir}}"/usr/share/fonts/OTF
       install -Dm644 ./*.otf \
         "${{targets.destdir}}"/usr/share/fonts/OTF
       # install provided config file with priority 61
       install -Dm755 -d "${{targets.destdir}}"/etc/fonts/conf.avail/
       install -Dm644 ./culmus.conf \
         "${{targets.destdir}}/etc/fonts/conf.avail/61-culmus.conf"
       # symlink for the abovementioned config file
       install -Dm755 -d "${{targets.destdir}}"/etc/fonts/conf.d
       ln -fs "../conf.avail/61-culmus.conf" "${{targets.destdir}}"/etc/fonts/conf.d/

update:
  enabled: true
  release-monitor:
    identifier: 10067
