package:
  name: diffoscope
  version: "258"
  epoch: 0
  description: "In-depth comparison of files, archives, and directories."
  copyright:
    - license: GPL-3.0-or-later
  dependencies:
    runtime:
      - py3-libarchive-c
      - py3-magic
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-docutils
      - py3-gpep517
      - py3-setuptools
      - py3-wheel
      - python3
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/d/diffoscope/diffoscope-${{package.version}}.tar.gz
      expected-sha256: 392788664f470924c70429283deb7e5d91ff270df055477534747216dd62ed59

  - runs: |
      python3 setup.py build

  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}" --skip-build

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 31806
