package:
  name: direnv
  version: 2.33.0
  epoch: 0
  description: unclutter your .profile
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 9f7e80649301aa10c1a0d5457bfda943e4b40b3a
      repository: https://github.com/direnv/direnv
      tag: v${{package.version}}

  - uses: go/build
    with:
      packages: .
      repository: https://github.com/direnv/direnv
      output: direnv

  - uses: strip

update:
  enabled: true
  github:
    identifier: direnv/direnv
    strip-prefix: v

test:
  pipeline:
    - runs: |
        direnv version
