package:
  name: docker-compose
  version: 2.24.6
  epoch: 0
  description: Define and run multi-container applications with Docker
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - btrfs-progs-dev
      - build-base
      - busybox
      - ca-certificates-bundle
      - containerd
      - coreutils
      - go
      - libseccomp-dev
      - libtool
      - linux-headers
      - lvm2-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/docker/compose
      tag: v${{package.version}}
      expected-commit: eb5f7d76fee2027bb4e25711e0d2666b3891dcd3

  - uses: go/bump
    with:
      deps: go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.46.0 go.opentelemetry.io/otel@v1.21.0 go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc@v1.21.0 go.opentelemetry.io/otel/sdk@v1.21.0

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin
      DESTDIR=${{targets.destdir}}/usr/bin/ make build

test:
  environment:
    contents:
      packages:
        - docker-cli
  pipeline:
    - runs: docker compose --help

update:
  enabled: true
  github:
    identifier: docker/compose
    strip-prefix: v
    tag-filter: v
