package:
  name: dpkg
  version: 1.22.5
  epoch: 0
  description: "The Debian Package Manager"
  copyright:
    - license: GPL-2.0-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - bzip2-dev
      - ca-certificates-bundle
      - gnutar # dpkg specifically needs GNU tar instead of bsdtar
      - libmd-dev
      - patch
      - perl
      - wolfi-base
      - xz
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      uri: http://ftp.de.debian.org/debian/pool/main/d/dpkg/dpkg_${{package.version}}.tar.xz
      expected-sha256: 26d27610536fdf951aa2be84503166c6ca8f6c36f71c049ab562ccca3233ca7e

  - runs: |
      ./configure \
        --build=$CBUILD \
        --host=$CHOST \
        --prefix=/usr \
        --sysconfdir=/etc \
        --mandir=/usr/share/man \
        --localstatedir=/var \
        --with-libz \
        --with-libbz2 \
        --disable-dselect \
        --disable-start-stop-daemon \
        --disable-nls

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "dpkg-dev"
    description: "headers for dpkg"
    pipeline:
      - uses: split/dev
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          mv "${{targets.destdir}}"/usr/bin/dpkg-architecture \
            "${{targets.destdir}}"/usr/bin/dpkg-buildpackage \
            "${{targets.destdir}}"/usr/bin/dpkg-checkbuilddeps \
            "${{targets.destdir}}"/usr/bin/dpkg-distaddfile \
            "${{targets.destdir}}"/usr/bin/dpkg-genchanges \
            "${{targets.destdir}}"/usr/bin/dpkg-gencontrol \
            "${{targets.destdir}}"/usr/bin/dpkg-gensymbols \
            "${{targets.destdir}}"/usr/bin/dpkg-name \
            "${{targets.destdir}}"/usr/bin/dpkg-scanpackages \
            "${{targets.destdir}}"/usr/bin/dpkg-scansources \
            "${{targets.destdir}}"/usr/bin/dpkg-shlibdeps \
            "${{targets.destdir}}"/usr/bin/dpkg-source \
            "${{targets.destdir}}"/usr/bin/dpkg-vendor \
            "${{targets.subpkgdir}}"/usr/bin/

          mkdir -p "${{targets.subpkgdir}}"/usr/share/
          mv "${{targets.destdir}}"/usr/share/perl* "${{targets.subpkgdir}}"/usr/share/
    dependencies:
      runtime:
        - dpkg

update:
  enabled: true
  release-monitor:
    identifier: 8127
