package:
  name: eza
  version: 0.18.4
  epoch: 0
  description: "A modern, maintained replacement for ls"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - libgit2-dev
      - rust
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/eza-community/eza
      tag: v${{package.version}}
      expected-commit: 1a36ca2de59ec2506a6ee15c53180be63bbe3ea2

  - runs: |
      cargo fetch
      cargo build --frozen --release

  - runs: |
      install -Dm755 target/release/eza "${{targets.destdir}}"/usr/bin/eza

  - uses: strip

update:
  enabled: true
  github:
    identifier: eza-community/eza
    strip-prefix: v
    tag-filter-prefix: v

test:
  environment:
    contents:
      packages:
        - wolfi-base
  pipeline:
    - runs: |
        eza
        eza --version
