package:
  name: file
  version: 5.43
  epoch: 0
  description: "file-type identification utility"
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: BSD-2-Clause
  dependencies:
    runtime:
environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/bootstrap/stage3
    keyring:
      - https://packages.wolfi.dev/bootstrap/stage3/wolfi-signing.rsa.pub
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - file
pipeline:
  - uses: fetch
    with:
      uri: http://ftp.astron.com/pub/file/file-${{package.version}}.tar.gz
      expected-sha256: 8c8015e91ae0e8d0321d94c78239892ef9dbc70c4ade0008c0e95894abfb1991
  - name: Configure
    runs: |
      ./configure \
         --host=${{host.triplet.gnu}} \
         --target=${{host.triplet.gnu}} \
         --prefix=/usr \
         --datadir=/usr/share
  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip
subpackages:
  - name: "libmagic-dev"
    description: "libmagic headers"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libmagic
  - name: "libmagic"
    description: "file-type guessing library"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/libmagic.so.* "${{targets.subpkgdir}}"/usr/lib

          mkdir -p "${{targets.subpkgdir}}"/usr/share
          mv "${{targets.destdir}}"/usr/share/misc "${{targets.subpkgdir}}"/usr/share
  - name: "file-doc"
    description: "file documentation"
    pipeline:
      - uses: split/manpages
