package:
  name: fluent-operator
  version: 3.0.0
  epoch: 1
  description: Operate Fluent Bit and Fluentd in the Kubernetes way - Previously known as FluentBit Operator
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/fluent/fluent-operator
      expected-commit: 1d758ceab090b13a3a807292aeebd6b2fdef391e
      tag: v${{package.version}}

  # until they cut a new release with that fix included
  # https://github.com/fluent/fluent-operator/pull/1294
  - uses: patch
    with:
      patches: 0001-re-add-accidently-removed-flag.Parse.patch

  - uses: go/build
    with:
      modroot: ./cmd/fluent-manager
      output: manager
      packages: .

  - uses: strip

subpackages:
  - name: fluent-watcher
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"/fluent-bit/config
      - uses: go/build
        with:
          packages: ./cmd/fluent-watcher/fluentbit
          output: fluent-watcher
          ldflags: -s -w
    test:
      environment:
        contents:
          packages:
            - fluent-bit
            - fluent-bit-compat
            - fluent-watcher-compat
      pipeline:
        - runs: |
            echo "Testing fluent-watcher"
            # Run fluent-watcher in the background and redirect its output to a temporary file
            tempfile=$(mktemp)
            fluent-watcher > "$tempfile" 2>&1 &

            # Capture the PID of fluent-watcher
            FLUENT_WATCHER_PID=$!

            sleep 5

            # Use grep to filter the output
            cat "$tempfile" | grep -i "fluent-bit started"

            # Wait for fluent-watcher to finish (optional)
            kill $FLUENT_WATCHER_PID

            # Clean up the temporary file
            rm "$tempfile"

  - name: fluent-watcher-compat
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"/fluent-bit/bin/
          ln -s /usr/bin/fluent-watcher "${{targets.contextdir}}"/fluent-bit/bin/fluent-watcher

update:
  enabled: true
  github:
    identifier: fluent/fluent-operator
    strip-prefix: v
    use-tag: true

test:
  environment:
    contents:
      packages:
        - curl
        - kwok
        - kwokctl
        - kubernetes # has a runtime dependency on kubectl
        - etcd
  pipeline:
    - uses: test/kwok/cluster
    - name: "Test operator"
      runs: |
        kubectl create ns fluent
        kubectl apply -f https://github.com/fluent/fluent-operator/releases/download/v${{package.version}}/setup.yaml
        manager -metrics-bind-address 0.0.0.0:8082&
        sleep 5; curl localhost:8082/metrics |grep workqueue_retries_total
