package:
  name: font-abyssinica
  version: 2.201
  epoch: 0
  description: A font for the Ethiopic script
  copyright:
    - license: OFL-1.0

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/silnrsi/font-abyssinica
      expected-commit: 7f131e8bd54befb412caa9e4874e05fcfa8cde7c
      tag: v${{package.version}}

  - runs: |
      pkgname=${{package.name}}
      mkdir -p "${{targets.destdir}}"/usr/share/fonts/${pkgname#font-}
      install -D -m644 ./references/*.ttf "${{targets.destdir}}"/usr/share/fonts/${pkgname#font-}

update:
  enabled: true
  github:
    identifier: silnrsi/font-abyssinica
    strip-prefix: v
