package:
  name: font-padauk
  version: 5.001
  epoch: 0
  description: Padauk pan Myanmar font
  copyright:
    - license: OFL-1.0

var-transforms:
  - from: ${{package.version}}
    match: (\d+)\.\d+
    replace: $1
    to: mangled-package-version

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/silnrsi/font-padauk
      expected-commit: 278b8efb03c0ca0d7f29fb3edc1f52489ebb384f
      tag: v${{package.version}}

  - runs: |
      pkgname=${{package.name}}
      mkdir -p "${{targets.destdir}}"/usr/share/fonts/${pkgname#font-}
      install -D -m644 ./references/v${{vars.mangled-package-version}}/*.ttf "${{targets.destdir}}"/usr/share/fonts/${pkgname#font-}

update:
  enabled: true
  github:
    identifier: silnrsi/font-padauk
    strip-prefix: v
