package:
  name: font-amiri
  version: 1.000
  epoch: 0
  description: Amiri (أميري) is a body text Naskh typeface
  copyright:
    - license: OFL-1.1

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/aliftype/amiri
      expected-commit: 45969ca9131d4c4200be89b1b71b9ec5d897264a
      tag: ${{package.version}}

  - runs: |
      pkgname=${{package.name}}
      mkdir -p "${{targets.destdir}}"/usr/share/fonts/${pkgname#font-}
      install -D -m644 ./fonts/*.ttf "${{targets.destdir}}"/usr/share/fonts/${pkgname#font-}

update:
  enabled: true
  github:
    identifier: aliftype/amiri
