package:
  name: gawk
  version: 5.2.1
  epoch: 0
  description: "GNU awk pattern-matching language"
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: GPL-3.0-or-later
  dependencies:
    runtime:
environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/bootstrap/stage3
    keyring:
      - https://packages.wolfi.dev/bootstrap/stage3/wolfi-signing.rsa.pub
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
pipeline:
  - uses: fetch
    with:
      uri: https://ftp.gnu.org/gnu/gawk/gawk-${{package.version}}.tar.gz
      expected-sha256: 529e7c8c6acf21ff3a6183f4d763c632810908989c24675c77995d51ac37b79c
  - name: Configure
    runs: |
      ./configure \
         --host=${{host.triplet.gnu}} \
         --target=${{host.triplet.gnu}} \
         --prefix=/usr \
         --datadir=/usr/share
  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip
