package:
  name: gc
  version: 8.2.6
  epoch: 0
  description: garbage collector for C and C++
  copyright:
    - license: Boehm-GC

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: fetch
    with:
      expected-sha256: b9183fe49d4c44c7327992f626f8eaa1d8b14de140f243edb1c9dcff7719a7fc
      uri: https://github.com/ivmai/bdwgc/releases/download/v${{package.version}}/gc-${{package.version}}.tar.gz

  - runs: |
      export CFLAGS="$CFLAGS -D_GNU_SOURCE -DNO_GETCONTEXT -DUSE_MMAP -DHAVE_DL_ITERATE_PHDR"
      ./configure \
        --host=${{host.triplet.gnu}} \
        --build=${{host.triplet.gnu}} \
        --prefix=/usr \
        --datadir=/usr/share/doc/gc \
        --enable-static \
        --enable-cplusplus

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: gc-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - gc
        - libgc++
    description: gc dev

  - name: gc-doc
    pipeline:
      - uses: split/manpages
    description: gc manpages

  - name: libgc++
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv ${{targets.destdir}}/usr/lib/libgccpp.* ${{targets.subpkgdir}}/usr/lib

update:
  enabled: true
  release-monitor:
    identifier: 336648
