package:
  name: gettext
  version: 0.22.5
  epoch: 0
  description: GNU locale utilities
  copyright:
    - license: GPL-3.0-or-later AND LGPL-2.1-or-later AND MIT
  dependencies:
    runtime:
      - glibc-iconv

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - libunistring-dev
      - libxml2-dev
      - ncurses-dev
      - perl

pipeline:
  - uses: fetch
    with:
      expected-sha256: fe10c37353213d78a5b83d48af231e005c4da84db5ce88037d88355938259640
      uri: https://ftp.gnu.org/gnu/gettext/gettext-${{package.version}}.tar.xz

  - uses: autoconf/configure
    with:
      opts: |
        --enable-threads=posix \
            --disable-java \
            --enable-static

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: gettext-doc
    pipeline:
      - uses: split/manpages
    description: gettext manpages

  - name: gettext-static
    pipeline:
      - uses: split/static
    description: gettext static

  - name: gettext-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - gettext
    description: gettext dev

update:
  enabled: true
  github:
    identifier: autotools-mirror/gettext
    strip-prefix: v
    use-tag: true
    tag-filter: v
