package:
  name: git-lfs
  version: 3.2.0
  epoch: 0
  description: "large file support for git"
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: MIT
  dependencies:
    runtime:
      - git
environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - go
      - git
pipeline:
  - uses: fetch
    with:
      uri: https://github.com/git-lfs/git-lfs/archive/v${{package.version}}.tar.gz
      expected-sha256: f8e6bbe043b97db8a5c16da7289e149a3fed9f4d4f11cffcc6e517c7870cd9e5
  - runs: |
      # mitigate CVE-2021-38561
      go get golang.org/x/text

      # mitigate CVE-2022-27191
      go get golang.org/x/crypto/ssh
  - runs: |
      make EXTRA_GO_FLAGS="-v -tags netcgo" GIT_LFS_SHA="v${{package.version}}" VERSION="v${{package.version}}"
  - runs: |
      install -Dm755 bin/git-lfs "${{targets.destdir}}"/usr/bin/git-lfs
  - uses: strip
