package:
  name: git
  version: 2.44.0
  epoch: 0
  description: "distributed version control system"
  copyright:
    - license: GPL-2.0-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - curl-dev
      - expat-dev
      - openssl-dev
      - pcre2-dev
      - wolfi-base
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      uri: https://www.kernel.org/pub/software/scm/git/git-${{package.version}}.tar.xz
      expected-sha256: e358738dcb5b5ea340ce900a0015c03ae86e804e7ff64e47aa4631ddee681de3

  - runs: |
      cat >> config.mak <<-EOF
      NO_GETTEXT=YesPlease
      NO_SVN_TESTS=YesPlease
      NO_REGEX=YesPlease
      NO_SYS_POLL_H=1
      ICONV_OMITS_BOM=Yes
      INSTALL_SYMLINKS=1
      USE_LIBPCRE2=YesPlease
      NO_PERL=YesPlease
      NO_TCLTK=YesPlease
      EOF

  - runs: |
      make prefix=/usr \
        CFLAGS="-O2 -Wall" \
        DESTDIR="${{targets.destdir}}" \
        INSTALLDIRS=vendor \
        install -j$(nproc)

  - runs: |
      mkdir -p "${{targets.destdir}}"/var/git

  - uses: strip

subpackages:
  - name: "git-daemon"
    description: "Git protocol daemon"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/libexec/git-core

          for i in git-daemon git-http-backend git-shell; do
            mv "${{targets.destdir}}"/usr/libexec/git-core/$i "${{targets.subpkgdir}}"/usr/libexec/git-core/
          done

          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/git-shell "${{targets.subpkgdir}}"/usr/bin/

  - name: "git-email"
    description: "Git tools for email"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/libexec/git-core

          for i in git-send-email git-imap-send; do
            mv "${{targets.destdir}}"/usr/libexec/git-core/$i "${{targets.subpkgdir}}"/usr/libexec/git-core/
          done

  - name: "git-p4"
    description: "Git tools for working with Perforce depots"
    dependencies:
      runtime:
        - git-daemon
    pipeline:
      - runs: |-
          mkdir -p "${{targets.subpkgdir}}"/usr/libexec/git-core/mergetools

          mv  "${{targets.destdir}}"/usr/libexec/git-core/*p4* "${{targets.subpkgdir}}"/usr/libexec/git-core/
          mv  "${{targets.destdir}}"/usr/libexec/git-core/mergetools/*p4* \
            "${{targets.subpkgdir}}"/usr/libexec/git-core/mergetools/

  - name: "git-completion"
    description: "Shell completion for git commands"
    dependencies:
      runtime:
        - git
    pipeline:
      - runs: |-
          mkdir -p "${{targets.contextdir}}"/usr/local/etc/profile.d/
          mv contrib/completion/* "${{targets.contextdir}}"/usr/local/etc/profile.d/
    test:
      environment:
        contents:
          packages:
            - wolfi-base
      pipeline:
        - runs: ls /usr/local/etc/profile.d/*.bash

test:
  environment:
    contents:
      packages:
        - wolfi-base
  pipeline:
    - runs: git --version

update:
  enabled: true
  release-monitor:
    identifier: 5350
