package:
  name: gitlab-kas-17.2
  version: 17.2.8
  epoch: 0
  description: GitLab KAS is a component installed together with GitLab. It is required to manage the GitLab agent for Kubernetes.
  copyright:
    - license: MIT
  dependencies:
    provides:
      - gitlab-kas=${{package.full-version}}

pipeline:
  - uses: git-checkout
    with:
      repository: https://gitlab.com/gitlab-org/cluster-integration/gitlab-agent
      tag: v${{package.version}}
      expected-commit: de30b93b8a50ecbe66ddfce3cab6489f42e5814e

  - uses: go/build
    with:
      packages: ./cmd/kas
      output: kas
      ldflags: "-w -X gitlab.com/gitlab-org/cluster-integration/gitlab-agent/v17/cmd.Version=v${{package.version}} -X gitlab.com/gitlab-org/cluster-integration/gitlab-agent/v17/cmd.Commit=v${{package.version}} -X gitlab.com/gitlab-org/cluster-integration/gitlab-agent/v17/cmd.BuildTime=$(date +%F-%T)"

update:
  enabled: true
  schedule:
    period: daily
    reason: upstream uses tags
  git:
    tag-filter-prefix: v17.2
    strip-prefix: v
