package:
  name: gitsign
  version: 0.8.1
  epoch: 1
  description: Keyless Git signing with Sigstore!
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/sigstore/gitsign/
      tag: v${{package.version}}
      expected-commit: bbd2c9c4ca1e1684fbabdead79d903ddc6caca92

  - uses: go/build
    with:
      packages: .
      output: gitsign

  - uses: strip

subpackages:
  - name: gitsign-credential-cache
    description: "helper binary that allows users to cache signing credentials"
    pipeline:
      - uses: go/build
        with:
          packages: ./cmd/gitsign-credential-cache
          output: gitsign-credential-cache
      - uses: strip

  - name: "${{package.name}}-config"
    description: "GitSign config"
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/etc/
          git config --system commit.gpgsign true       # Sign all commits
          git config --system tag.gpgsign true          # Sign all tags
          git config --system gpg.x509.program gitsign  # Use gitsign for signing
          git config --system gpg.format x509           # gitsign expects x509 args
          cp /etc/gitconfig ${{targets.subpkgdir}}/etc

update:
  enabled: true
  github:
    identifier: sigstore/gitsign
    strip-prefix: v
