package:
  name: grype
  version: 0.74.7
  epoch: 0
  description: Vulnerability scanner for container images, filesystems, and SBOMs
  copyright:
    - license: Apache-2.0

environment:
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/anchore/grype
      tag: v${{package.version}}
      expected-commit: 987238519b8d6e302130ab715f20daed6634da68

  - uses: go/build
    with:
      ldflags: -w -X main.version=${{package.version}}
      output: grype
      packages: ./cmd/grype

  - uses: strip

update:
  enabled: true
  github:
    identifier: anchore/grype
    strip-prefix: v

test:
  pipeline:
    - runs: |
        grype --version
