package:
  name: hugo
  version: 0.123.3
  epoch: 0
  description: The world's fastest framework for building websites.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - git

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/gohugoio/hugo
      tag: v${{package.version}}
      expected-commit: a75a659f6fc0cb3a52b2b2ba666a81f79a459376

  - uses: go/build
    with:
      packages: .
      output: hugo

  - uses: strip

update:
  enabled: true
  github:
    identifier: gohugoio/hugo
    strip-prefix: v
