package:
  name: icu
  version: !!float 72-1
  epoch: 0
  description: "International Components for Unicode library"
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: MIT
  dependencies:
    runtime:
environment:
  contents:
    packages:
      - busybox
      - build-base
      - ca-certificates-bundle
  environment:
    ICU_DATA_FILTER_FILE: "./data-filter-en.json"
pipeline:
  - uses: fetch
    with:
      # TODO: cannot use package.version here since "71-1"/"71_1" are different from "71.1"
      uri: https://github.com/unicode-org/icu/releases/download/release-71-1/icu4c-71_1-src.tgz
      expected-sha512: 1fd2a20aef48369d1f06e2bb74584877b8ad0eb529320b976264ec2db87420bae242715795f372dbc513ea80047bc49077a064e78205cd5e8b33d746fd2a2912
  - runs: |
      # JSON-ified version of https://git.alpinelinux.org/aports/plain/main/icu/data-filter-en.yml?id=8db8f1a746ebc18ac3b56c91ed14224e424f57ec
      echo '{"localeFilter":{"filterType":"locale","includeChildren":false,"includelist":["en_US","en_GB"]},"featureFilters":{"brkitr_dictionaries":"exclude","brkitr_rules":{"filterType":"regex","excludelist":["^.*_cj$"]},"coll_tree":{"filterType":"language","includelist":["be","cs","de","el","en","es","ff","fr","ha","hu","ig","it","kk","ms","nl","pl","pt","ro","ru","tr","uk","xh","zu"]},"conversion_mappings":"exclude","stringprep":{"excludelist":["rfc3722","rfc3920node","rfc3920res"]}},"resourceFilters":[{"categories":["coll_tree"],"rules":["-/collations/emoji","-/collations/private-unihan"]},{"categories":["translit"],"rules":["-/","+/%%Parent","+/%%ALIAS","+/*/ASCII-Latin","+/*/Latin-ASCII","+/*/Accents-Any","+/*/Any-Accents","+/*/Publishing-Any","+/*/Any-Publishing","+/*/Cyrillic-Latin","+/*/Cyrl-Latn","+/*/Latin-Cyrillic","+/*/Latn-Cyrl","+/*/Greek-Latin","+/*/Grek-Latn","+/*/Greek-Latin/BGN","+/*/el-el_Latn/BGN","+/*/Latin-Greek","+/*/Latn-Grek","+/*/Russian-Latin/BGN","+/*/ru-ru_Latn/BGN","+/*/Latin-Russian/BGN","+/*/ru_Latn-ru/BGN","+/*/Ukrainian-Latin/BGN","+/*/uk-uk_Latn/BGN","+/*/de-ASCII","+/*/de-t-de-d0-ascii"]}],"collationUCAData":"implicithan"}' > ./source/data-filter-en.json
  - uses: autoconf/configure
    with:
      dir: source
      opts: |
        --build=${{host.triplet.gnu}} \
        --host=${{host.triplet.gnu}} \
        --sysconfdir=/etc \
        --with-data-packaging=archive \
        --disable-samples \
        --enable-static \
        --mandir=/usr/share/man
  - uses: autoconf/make-install
    with:
      dir: source
  - uses: strip
subpackages:
  - name: icu-dev
    description: icu development headers
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - icu
