package:
  name: istio-operator-1.19
  version: 1.19.7
  epoch: 1
  description: Istio operator provides user friendly options to operate the Istio service mesh
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - istio-operator=1.19

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/istio/istio
      tag: ${{package.version}}
      expected-commit: 42b7d96f3587652551b302499e1c8761bc3a0b49

  - uses: patch
    with:
      patches: bump.patch

  - uses: go/bump
    with:
      deps: github.com/lestrrat-go/jwx@v1.2.28 helm.sh/helm/v3@v3.14.2
      replaces: go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp=go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp@v1.19.0
      go-version: 1.21
      show-diff: true

  - uses: go/build
    with:
      packages: ./operator/cmd/operator
      output: operator

  - runs: |
      mkdir -p ${{targets.destdir}}/var/lib/istio
      mv manifests ${{targets.destdir}}/var/lib/istio/manifests

  - uses: strip

update:
  enabled: true
  github:
    identifier: istio/istio
    tag-filter: 1.19.
    use-tag: true
