package:
  name: istio-operator-1.20
  version: 1.20.3
  epoch: 2
  description: Istio operator provides user friendly options to operate the Istio service mesh
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - istio-operator=1.20

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/istio/istio
      tag: ${{package.version}}
      expected-commit: 692e556046b48ebc471205211c68a2c69e74a321

  # patch changes sourced from here: https://github.com/istio/istio/commit/9878f6fb7fc790c4447e870684ccb8477f280561#diff-465739ea8d3af036c51f1333efa69f32f818775746c405cc8c49789f2fa065c1
  - uses: patch
    with:
      patches: bump.patch

  - uses: go/bump
    with:
      deps: helm.sh/helm/v3@v3.14.2

  - uses: go/build
    with:
      packages: ./operator/cmd/operator
      output: operator

  - runs: |
      mkdir -p ${{targets.destdir}}/var/lib/istio
      mv manifests ${{targets.destdir}}/var/lib/istio/manifests

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - '-rc'
    - '-beta'
  github:
    identifier: istio/istio
    tag-filter-prefix: 1.20.
    use-tag: true
