package:
  name: jitsucom-bulker
  version: 2.7.0
  epoch: 2
  description: Service for bulk-loading data to databases with automatic schema management (Redshift, Snowflake, BigQuery, ClickHouse, Postgres, MySQL)
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - jitsucom-bulker-bulker
      - jitsucom-bulker-ingest
      - jitsucom-bulker-ingmgr
      - jitsucom-bulker-sidecar
      - jitsucom-bulker-syncctl

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 09d94c65d132dd4c5c8f052b8b74138a5e772e17
      repository: https://github.com/jitsucom/bulker
      tag: jitsu2-v${{package.version}}

  - uses: go/bump
    with:
      # Mitigate CVE-2023-45288
      deps: golang.org/x/net@v0.23.0
      modroot: ingest

  - uses: go/bump
    with:
      # Mitigate CVE-2023-45288
      deps: golang.org/x/net@v0.23.0
      modroot: ingress-manager

  - uses: go/bump
    with:
      # Mitigate CVE-2023-45288
      deps: golang.org/x/net@v0.23.0
      modroot: sync-controller

  - uses: go/bump
    with:
      # Mitigate GHSA-6294-6rgp-fr7r
      deps: github.com/dvsekhvalnov/jose2go@v1.6.0
      modroot: bulkerlib

data:
  - name: commands
    items:
      bulker: bulkerapp
      ingest: ingest
      sidecar: sync-sidecar
      syncctl: sync-controller
      ingmgr: ingress-manager

subpackages:
  - range: commands
    name: "${{package.name}}-${{range.key}}"
    pipeline:
      - uses: go/build
        with:
          modroot: ./${{range.value}}
          packages: .
          ldflags: -s -w -X main.Commit=$(git rev-parse HEAD) -X main.Timestamp=$(date '+%F_%H:%M:%S')
          output: ${{range.key}}

  - range: commands
    name: "${{package.name}}-${{range.key}}-compat"
    description: "Compatibility package to place binaries in the location expected by upstream"
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"/app
          ln -sf /usr/bin/${{range.key}} "${{targets.contextdir}}"/app/${{range.key}}

update:
  enabled: true
  ignore-regex-patterns:
    - -beta.*
  git:
    strip-prefix: jitsu2-v
    tag-filter-prefix: jitsu2-v

test:
  environment:
    contents:
      packages:
        - ${{package.name}}-bulker
        - ${{package.name}}-ingest
        - ${{package.name}}-sidecar
        - ${{package.name}}-syncctl
        - ${{package.name}}-ingmgr
  pipeline:
    - runs: |
        # We expect some commands to fail, but want its output anyway.
        # The commands are not intended to run directly.
        set +o pipefail
        /usr/bin/bulker 2>&1 | grep -q "Starting bulker app"
        /usr/bin/ingest 2>&1 | grep -q "Generated instance id"
        /usr/bin/sidecar 2>&1 | grep -q "dial error" # It's OK to fail, as it tries to connect to a non-existent postgres socket
        /usr/bin/syncctl 2>&1 | grep -q "unable to load in-cluster configuration"
        /usr/bin/ingmgr 2>&1 | grep -q "Generated instance id"
