package:
  name: jvmkill
  version: 0.0.2_git20241018
  epoch: 0
  description: Terminate the JVM when resources are exhausted
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - make
      - openjdk-17
      - openjdk-17-default-jvm

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/airlift/jvmkill
      branch: master
      expected-commit: 8a6ae95b38905f98ce6b7b727efb2dc75da16e11

  - runs: |
      export JAVA_HOME=/usr/lib/jvm/java-17-openjdk
      make all
      mkdir -p ${{targets.destdir}}/usr/lib
      mv libjvmkill.so ${{targets.destdir}}/usr/lib/

update:
  enabled: true
  git: {}
  schedule:
    period: daily
    reason: upstream does not support tags or releases
