package:
  name: k9s
  version: 0.31.9
  epoch: 1
  description: Kubernetes CLI To Manage Your Clusters In Style!
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      expected-commit: f2f4077b592dcbb4162cbfe07bd99546d47d9955
      repository: https://github.com/derailed/k9s
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: helm.sh/helm/v3@v3.14.2

  - uses: go/build
    with:
      packages: .
      ldflags: -s -w -X github.com/derailed/k9s/cmd.version=v${{package.version}} -X github.com/derailed/k9s/cmd.commit=$(git rev-parse HEAD) -X github.com/derailed/k9s/cmd.date=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
      repository: https://github.com/derailed/k9s
      output: k9s

  - uses: strip

update:
  enabled: true
  github:
    identifier: derailed/k9s
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - wolfi-base
  pipeline:
    - runs: |
        k9s version
