# See https://github.com/kedacore/keda/blob/main/SECURITY.md#supported-versions for upstream-supported versions
package:
  name: keda
  version: 2.13.1
  epoch: 0
  description: KEDA is a Kubernetes-based Event Driven Autoscaling component. It provides event driven scale for any container running in Kubernetes
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - tzdata

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
      - protobuf-dev
      - protoc

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 41dd7a8558fdb274f2c0861f6c6d1eba01f2dcd5
      repository: https://github.com/kedacore/keda
      tag: v${{package.version}}

  - runs: |
      ARCH=$(go env GOARCH) make build
      mkdir -p "${{targets.destdir}}/usr/bin"
      mv bin/keda "${{targets.destdir}}/usr/bin"

  - uses: strip

subpackages:
  - name: "${{package.name}}-adapter"
    description: "Metrics adapter for Keda"
    dependencies:
      runtime:
        - tzdata
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/usr/bin"
          mv bin/keda-adapter "${{targets.subpkgdir}}/usr/bin"
      - uses: strip

  - name: "${{package.name}}-admission-webhooks"
    description: "Webhooks for Keda"
    dependencies:
      runtime:
        - tzdata
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/usr/bin"
          mv bin/keda-admission-webhooks "${{targets.subpkgdir}}/usr/bin"
      - uses: strip

  - name: "${{package.name}}-compat"
    description: "Compatibility package to place binaries in the location expected by upstream helm charts"
    pipeline:
      - runs: |
          # The helm chart expects the keda binaries to be in / instead of /usr/bin
          mkdir -p "${{targets.subpkgdir}}"
          ln -sf /usr/bin/keda ${{targets.subpkgdir}}/keda
          ln -sf /usr/bin/keda-admission-webhooks ${{targets.subpkgdir}}/keda-admission-webhooks
          ln -sf /usr/bin/keda-adapter ${{targets.subpkgdir}}/keda-adapter
      - uses: strip

update:
  enabled: true
  github:
    identifier: kedacore/keda
    strip-prefix: v
