package:
  name: lcov
  version: "2.1"
  epoch: 1
  description: LCOV is an extension to GCOV. It provides a graphical frontend for converage information
  copyright:
    - license: GPL-2.0-or-later
  dependencies:
    runtime:
      - bash
      - perl
      - perl-capture-tiny
      - perl-datetime
      - perl-devel-cover
      - perl-digest-md5
      - perl-json-xs
      - perl-memory-process
      - perl-time-hires

environment:
  contents:
    packages:
      - autoconf
      - automake
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - perl
      - perl-capture-tiny
      - perl-date-format
      - perl-datetime
      - perl-digest-md5
      - perl-json-xs
      - perl-memory-process
      - perl-test-simple
      - perl-time-hires

pipeline:
  - uses: fetch
    with:
      expected-sha256: 4d01d9f551a3f0e868ce84742fb60aac4407e3fc1622635a07e29d70e38f1faf
      uri: https://github.com/linux-test-project/lcov/releases/download/v${{package.version}}/lcov-${{package.version}}.tar.gz

  - runs: |
      # Not using perl pipeline since it doesn't use Makefile.PL
      make DESTDIR=${{targets.destdir}} PREFIX="/usr" install

  - uses: strip

subpackages:
  - name: lcov-doc
    pipeline:
      - uses: split/manpages
    description: lcov manpages

update:
  enabled: true
  github:
    identifier: linux-test-project/lcov
    strip-prefix: v
    use-tag: true
