package:
  name: libbsd
  version: 0.12.1
  epoch: 0
  description: commonly-used BSD functions not implemented by all libcs
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - libmd-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: d7747f8ec1baa6ff5c096a9dd587c061233dec90da0f1aedd66d830f6db6996a
      uri: https://libbsd.freedesktop.org/releases/libbsd-${{package.version}}.tar.xz

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: libbsd-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libmd-dev
        - libbsd
    description: libbsd dev

  - name: libbsd-doc
    pipeline:
      - uses: split/manpages
    description: libbsd manpages

update:
  enabled: true
  release-monitor:
    identifier: 1567
