package:
  name: libffi
  version: 3.4.4
  epoch: 0
  description: "portable foreign function interface library"
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: MIT
  dependencies:
    runtime:
environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/bootstrap/stage3
    keyring:
      - https://packages.wolfi.dev/bootstrap/stage3/wolfi-signing.rsa.pub
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - texinfo
pipeline:
  - uses: fetch
    with:
      uri: https://github.com/libffi/libffi/releases/download/v${{package.version}}/libffi-${{package.version}}.tar.gz
      expected-sha256: d66c56ad259a82cf2a9dfc408b32bf5da52371500b84745f7fb8b645712df676
  - name: Configure
    runs: |
      ./configure \
         --host=${{host.triplet.gnu}} \
         --target=${{host.triplet.gnu}} \
         --prefix=/usr \
         --datadir=/usr/share \
         --enable-portable-binary \
         --enable-pax_emutramp \
         --disable-exec-static-tramp
  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip
subpackages:
  - name: "libffi-dev"
    description: "libffi headers"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libffi
