package:
  name: libgpg-error
  version: "1.48"
  epoch: 0
  description: Support library for libgcrypt
  copyright:
    - license: GPL-2.0-or-later AND LGPL-2.1-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: fetch
    with:
      expected-sha256: 89ce1ae893e122924b858de84dc4f67aae29ffa610ebf668d5aa539045663d6f
      uri: https://gnupg.org/ftp/gcrypt/libgpg-error/libgpg-error-${{package.version}}.tar.bz2

  - uses: autoconf/configure
    with:
      opts: |
        --disable-nls \
        --enable-static \
        --sysconfdir=/etc

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: libgpg-error-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libgpg-error
    description: libgpg-error dev

update:
  enabled: true
  release-monitor:
    identifier: 1628
