package:
  name: libksba
  version: 1.6.6
  epoch: 0
  description: Libksba is a CMS and X.509 access library
  copyright:
    - license: GPL-2.0-or-later OR GPL-3.0-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - libgpg-error-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: 5dec033d211559338838c0c4957c73dfdc3ee86f73977d6279640c9cd08ce6a4
      uri: https://www.gnupg.org/ftp/gcrypt/libksba/libksba-${{package.version}}.tar.bz2

  - uses: autoconf/configure
    with:
      opts: |
        --host=${{host.triplet.gnu}} \
        --build=${{host.triplet.gnu}} \

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: libksba-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libksba
    description: libksba dev

  - name: libksba-doc
    pipeline:
      - uses: split/manpages
      - uses: split/infodir
    description: libksba manpages

update:
  enabled: true
  release-monitor:
    identifier: 1649
