package:
  name: libpng
  version: 1.6.39
  epoch: 0
  description: Portable Network Graphics library
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: Libpng
environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - automake
      - autoconf
      - zlib-dev
      - gawk
      - libtool
pipeline:
  - uses: fetch
    with:
      expected-sha256: 5400b88c81e71ccb4d35fd679c036072fe027eb2ae6af0622d57926c4d089281
      uri: https://downloads.sourceforge.net/libpng/libpng-${{package.version}}.tar.gz
  - runs: autoreconf -vif
  - uses: autoconf/configure
  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip
subpackages:
  - name: libpng-doc
    pipeline:
      - uses: split/manpages
    description: libpng manpages
  - name: libpng-static
    description: libpng static library
    pipeline:
      - uses: split/static
  - name: libpng-utils
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/share
          mv ${{targets.destdir}}/usr/bin ${{targets.subpkgdir}}/usr/
    description: libpng utils
  - name: libpng-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libpng
    description: libpng dev
