package:
  name: libspiro
  version: "20221101"
  epoch: 0
  description: Library to simplify the drawing of beautiful curves
  copyright:
    - license: GPL-3.0-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - libtool

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/fontforge/libspiro
      expected-commit: 0d87bd211eb22dc3445c263fbf6afba158f14084
      tag: ${{package.version}}

  - runs: autoreconf -i -f

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: libspiro-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libspiro
    description: libspiro dev

  - name: libspiro-doc
    pipeline:
      - uses: split/manpages
    description: libspiro manpages

update:
  enabled: true
  github:
    identifier: fontforge/libspiro
