package:
  name: libx11
  version: 1.8.2
  epoch: 0
  description: X11 client-side library
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: custom:XFREE86
environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - automake
      - autoconf
      - libxcb-dev
      - xtrans
      - xorgproto
      - util-macros
      - xmlto
pipeline:
  - uses: fetch
    with:
      expected-sha256: ed91d573d570db83b8ae546f4890dccfcd0b9dfe1e50a1b401b63a74c152ed04
      uri: https://www.x.org/releases/individual/lib/libX11-${{package.version}}.tar.xz
  - uses: autoconf/configure
    with:
      opts: |
        --with-xcb \
        --disable-thread-safety-constructor
  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip
subpackages:
  - name: libx11-static
    description: libx11 static library
    pipeline:
      - uses: split/static
  - name: libx11-doc
    pipeline:
      - uses: split/manpages
    description: libx11 manpages
  - name: libx11-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libx11
        - libxcb-dev
        - xtrans
    description: libx11 dev
