package:
  name: linkerd-await
  version: 0.2.8
  epoch: 0
  description: "A program that blocks on linkerd readiness"
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - rust

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/linkerd/linkerd-await
      tag: release/v${{package.version}}
      expected-commit: 880850995004e1c5b1f29fccdfdcbd4f45cb7ec2

  - runs: |
      cargo fetch
      cargo build --frozen --release
      mkdir -p ${{targets.destdir}}/usr/bin
      mv target/release/linkerd-await ${{targets.destdir}}/usr/bin

  - uses: strip

update:
  enabled: true
  github:
    identifier: linkerd/linkerd-await
    strip-prefix: release/v

test:
  pipeline:
    - runs: |
        linkerd-await --version | grep ${{package.version}}
