package:
  name: linux-pam
  version: 1.6.0
  epoch: 1
  description: Linux PAM (Pluggable Authentication Modules for Linux)
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - autoconf
      - automake
      - bison
      - build-base
      - busybox
      - ca-certificates-bundle
      - flex-dev
      - gettext-dev
      - libtool

pipeline:
  - uses: fetch
    with:
      expected-sha256: fff4a34e5bbee77e2e8f1992f27631e2329bcbf8a0563ddeb5c3389b4e3169ad
      uri: https://github.com/linux-pam/linux-pam/releases/download/v${{package.version}}/Linux-PAM-${{package.version}}.tar.xz

  - uses: autoconf/configure
    with:
      opts: |
        --sysconfdir=/etc \
            --mandir=/usr/share/man \
            --infodir=/usr/share/info \
            --localstatedir=/var \
            --disable-nls \
            --disable-db

  - uses: autoconf/make

  - uses: autoconf/make-install

  - runs: |
      # install our pam.d files
      mkdir -p ${{targets.destdir}}/etc/pam.d
      for pam_conf in *.pamd; do
        mv "${pam_conf}" ${{targets.destdir}}/etc/pam.d/"${pam_conf%.pamd}"
      done

      # make "unix_chkpwd" shadow group and enable g+s
      chgrp shadow ${{targets.destdir}}/sbin/unix_chkpwd \
        && chmod g+s ${{targets.destdir}}/sbin/unix_chkpwd

      # we don't ship systemd
      rm -r ${{targets.destdir}}/usr/lib/systemd

subpackages:
  - name: linux-pam-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - linux-pam
        - gettext-dev
    description: linux-pam dev

  - name: linux-pam-doc
    pipeline:
      - uses: split/manpages
    description: linux-pam manpages

update:
  enabled: true
  github:
    identifier: linux-pam/linux-pam
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - util-linux
        - shadow
  pipeline:
    - runs: |
        # Suppress expired passwd warning
        if su 1>/dev/null; then
          printf "Test succeeded!"
        else
          printf "Test failed! Invalid PAM configuration."
        fi
