package:
  name: linux-headers
  version: 5.19.17
  epoch: 0
  description: "the Linux kernel headers (cross compilation)"
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: GPL-3.0-or-later
  dependencies:
    runtime:
environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/bootstrap/stage3
    keyring:
      - https://packages.wolfi.dev/bootstrap/stage3/wolfi-signing.rsa.pub
    packages:
      - wolfi-baselayout
      - busybox
      - build-base
      - scanelf
      - ca-certificates-bundle
pipeline:
  - uses: fetch
    with:
      uri: https://www.kernel.org/pub/linux/kernel/v5.x/linux-${{package.version}}.tar.gz
      expected-sha256: f201873920873bcd3c62b4d1bf2091d0ca00ff3c81cb3a1063d38d23058f6062
  - runs: |
      make mrproper
  - runs: |
      make headers
      find usr/include -name '.*' -delete
      rm usr/include/Makefile

      # Copy to cross-sysroot
      mkdir -p ${{targets.destdir}}/usr/include
      cp -rv usr/include/* ${{targets.destdir}}/usr/include/
