package:
  name: lua-luv
  version: 1.48.0.1
  epoch: 0
  description: "Bare libuv bindings for Lua"
  copyright:
    - license: Apache-2.0

# transform melange version 1.45.0.0 => 1.45.0-0
var-transforms:
  - from: ${{package.version}}
    match: \.(\d+)$
    replace: -$1
    to: mangled-package-version

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - libuv-dev
      - luajit-dev
      - samurai
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/luvit/luv
      tag: ${{vars.mangled-package-version}}
      expected-commit: 693951ef762058a8a9fdc76ef7d9e465d6bdd8cc

  - runs: |
      # TODO: Package lua-compat5.3
      make deps/lua-compat-5.3/c-api

      cmake -B build -G Ninja \
        -DWITH_SHARED_LIBUV=ON \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DLUA_BUILD_TYPE=System \
        -DBUILD_MODULE=OFF \
        -DLUA_COMPAT53_DIR=deps/lua-compat-5.3 \
        -DBUILD_SHARED_LIBS=ON

      cmake --build build
      DESTDIR="${{targets.destdir}}" cmake --install build

  - runs: |
      rockdir=${{targets.destdir}}/usr/lib/luarocks/rocks-common/luv/${{vars.mangled-package-version}}
      mkdir -p $rockdir
      echo "rock_manifest = {}" > "$rockdir"/rock_manifest

subpackages:
  - name: lua-luv-dev
    pipeline:
      - uses: split/dev
    description: lua-luv dev

update:
  enabled: true
  version-transform:
    - match: \-
      replace: .
  github:
    identifier: luvit/luv
    strip-prefix: v
    use-tag: true
