package:
  name: mariadb-connector-c
  version: 3.3.8
  epoch: 1
  description: The MariaDB Native Client library (C driver)
  copyright:
    - license: LGPL-2.1-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - openssl-dev
      - samurai
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: f9f076b4aa9fb22cc94b24f82c80f9ef063805ecd6533a2eb5d5060cf93833e8
      uri: https://mirror.vpsfree.cz/mariadb/connector-c-${{package.version}}/mariadb-connector-c-${{package.version}}-src.tar.gz

  - runs: |
      # INSTALL_LIBDIR and INSTALL_INCLUDEDIR are relative to CMAKE_INSTALL_PREFIX.
      cmake -B build -G Ninja \
        -DCMAKE_BUILD_TYPE=MinSizeRel \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DBUILD_SHARED_LIBS=True \
        -DINSTALL_LIBDIR=lib \
        -DINSTALL_INCLUDEDIR=include/mysql \
        \
        -DMARIADB_PORT=3306 \
        -DMARIADB_UNIX_ADDR=/run/mysqld/mysqld.sock \
        -DWITH_EXTERNAL_ZLIB=YES \
        -DWITH_MYSQLCOMPAT=ON \
        -DWITH_SSL=OPENSSL \
        $CMAKE_CROSSOPTS
      cmake --build build
      echo 1

  - runs: |
      DESTDIR="${{targets.destdir}}" cmake --install build

      # purge static libs
      rm "${{targets.destdir}}"/usr/lib/*.a

      # Docs conflict with mariadb-doc
      rm -r "${{targets.destdir}}"/usr/man

      # compat symlinks
      ln -s mariadb_config "${{targets.destdir}}"/usr/bin/mysql_config
      ln -s mariadb_version.h "${{targets.destdir}}"/usr/include/mysql/mysql_version.h

  - uses: strip

subpackages:
  - name: mariadb-connector-c-dev
    pipeline:
      - uses: split/dev
    dependencies:
      replaces:
        - mariadb-dev
    description: mariadb-connector-c dev

update:
  enabled: true
  release-monitor:
    identifier: 16939
