# When bumping the version check if the CVE/GHSA mitigations below can be removed.
package:
  name: melange
  version: 0.6.4
  epoch: 0
  description: build APKs from source code
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - bubblewrap
      - busybox
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 49264c764db801371d44023b72bdaa9d5c2c4174
      repository: https://github.com/chainguard-dev/melange
      tag: v${{package.version}}

  - runs: |
      make melange
      install -m755 -D ./melange "${{targets.destdir}}"/usr/bin/melange

  - uses: strip

update:
  enabled: true
  github:
    identifier: chainguard-dev/melange
    strip-prefix: v
    use-tag: true
