package:
  name: memcached
  version: 1.6.24
  epoch: 0
  description: "Distributed memory object caching system"
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cyrus-sasl-dev
      - libevent-dev
      - libseccomp-dev
      - linux-headers
      # - bsd-compat-headers
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://www.memcached.org/files/memcached-${{package.version}}.tar.gz
      expected-sha512: e43386c2a6c0b95cefdccfe7f6b3890c59ca8b5c2636efc2e910b9617b20a5cf6de9bfedaafe0fb05c91bebb175fbdf033f5e0e512cb041b73af5af0d1854265

  - uses: autoconf/configure
    with:
      opts: |
        --build=$CBUILD \
        --host=$CHOST \
        --prefix=/usr \
        --enable-sasl \
        --enable-sasl-pwdb \
        --enable-seccomp

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "memcached-dev"
    description: "headers for memcached"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - memcached

  - name: "memcached-doc"
    description: "memcached manpages"
    pipeline:
      - uses: split/manpages

  - name: memcached-bitnami-compat
    description: "compat package with bitnami/memcached image"
    pipeline:
      - uses: bitnami/compat
        with:
          image: memcached
          version-path: 1/debian-11
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/opt/bitnami/memcached/conf/sasl2

update:
  enabled: true
  github:
    identifier: memcached/memcached
    use-tag: true
    tag-filter: 1.
