package:
  name: meson
  version: 0.64.1
  epoch: 0
  description: Fast and user friendly build system
  target-architecture:
    - all
  copyright:
    - paths:
        - '*'
      attestation: TODO
      license: Apache-2.0
  dependencies:
    runtime:
      - python3
      - samurai
environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3
      - samurai
pipeline:
  - uses: fetch
    with:
      expected-sha256: 3a8e030c2334f782085f81627062cc6d4a6771edf31e055ffe374f9e6b089ab9
      uri: https://github.com/mesonbuild/meson/releases/download/${{package.version}}/meson-${{package.version}}.tar.gz
  - runs: python3 setup.py build
  - runs: python3 setup.py install --prefix=/usr --root=${{targets.destdir}}
  - uses: strip
subpackages:
  - name: meson-doc
    pipeline:
      - uses: split/manpages
    description: meson manpages
