package:
  name: mpfr
  version: 4.1.1
  epoch: 0
  description: "multiple-precision floating-point library"
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: LGPL-3.0-or-later
  dependencies:
    runtime:
environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/bootstrap/stage3
    keyring:
      - https://packages.wolfi.dev/bootstrap/stage3/wolfi-signing.rsa.pub
    packages:
      - wolfi-baselayout
      - busybox
      - build-base
      - ca-certificates-bundle
      - texinfo
      - gmp-dev
pipeline:
  - uses: fetch
    with:
      uri: https://www.mpfr.org/mpfr-${{package.version}}/mpfr-${{package.version}}.tar.xz
      expected-sha256: ffd195bd567dbaffc3b98b23fd00aad0537680c9896171e44fe3ff79e28ac33d
  - runs: |
      ./configure \
        --host=${{host.triplet.gnu}} \
        --target=${{host.triplet.gnu}} \
        --prefix=/usr \
        --enable-shared
  - uses: autoconf/make
  - uses: autoconf/make-install
  - name: 'Clean up documentation'
    runs: |
      rm -rf ${{targets.destdir}}/usr/share/info
subpackages:
  - name: "mpfr-dev"
    description: "mpfr headers"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - mpfr
