package:
  name: numpy
  version: 1.26.4
  epoch: 2
  description: "The fundamental package for scientific computing with Python."
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - cython
      - gfortran
      - git
      - meson
      - openblas-dev
      - py3-gpep517
      - py3-packaging
      - py3-pip
      - py3-setuptools
      - py3-wheel
      - python3
      - python3-dev
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/numpy/numpy
      tag: v${{package.version}}
      expected-commit: 9815c16f449e12915ef35a8255329ba26dacd5c0
      recurse-submodules: true

  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

subpackages:
  - name: f2py
    description: "f2py for numpy (for python3)"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/f2py* "${{targets.subpkgdir}}"/usr/bin
    dependencies:
      runtime:
        - python3-dev
        - numpy

update:
  enabled: true
  github:
    identifier: numpy/numpy
    # There are some v2 pre-releases
    tag-filter: v1
    strip-prefix: v
    strip-suffix: .dev0
