package:
  name: nvm
  version: 0.39.7
  epoch: 0
  description: Node Version Manager
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - coreutils
      - libstdc++ # for node itself
      - wget

environment:
  contents:
    packages:
      - bash
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/nvm-sh/nvm
      expected-commit: bab86d5de571015b63fd8fc30b47bbe072a1290e
      tag: v${{package.version}}

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/share/nvm
      chmod +x nvm.sh
      mv nvm.sh ${{targets.destdir}}/usr/share/nvm

update:
  enabled: true
  github:
    identifier: nvm-sh/nvm
    strip-prefix: v

test:
  pipeline:
    - runs: |
        source /usr/share/nvm/nvm.sh
        nvm install v14
        node --version | grep v14
