package:
  name: ollama
  version: 0.3.5
  epoch: 0
  description: Get up and running with Llama 2 and other large language models locally
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/ollama/ollama
      tag: v${{package.version}}
      expected-commit: 15c2d8fe149ba2b58aadbab615a6955f8821c7a9

  - runs: |
      go generate ./...
      CGO_ENABLED=1 go build -ldflags '-linkmode external -extldflags "-static"' .
      mkdir -p ${{targets.destdir}}/usr/bin
      mv ollama ${{targets.destdir}}/usr/bin

  - uses: strip

update:
  enabled: true
  github:
    identifier: ollama/ollama
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - curl
  pipeline:
    - name: Start ollama server
      runs: |
        # Start the ollama server in the background
        ollama serve &
        SERVER_PID=$!
        sleep 5

        # Check if the server is running
        curl -s localhost:11434 | grep -q "Ollama is running"

        # Kill the server process
        kill $SERVER_PID
