package:
  name: opentelemetry-collector-contrib
  version: 0.95.0
  epoch: 0
  description: Contrib repository for the OpenTelemetry Collector
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/open-telemetry/opentelemetry-collector-contrib
      tag: v${{package.version}}
      expected-commit: be5986fd93aded30a3522cb6b91c71e16bd1e7e8

  - runs: make otelcontribcol

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin
      mv bin/otelcontribcol* ${{targets.destdir}}/usr/bin/otelcol-contrib

  - uses: strip

subpackages:
  - name: opentelemetry-collector-contrib-compat
    description: "Compatibility package to place binaries in the location expected by upstream helm charts"
    pipeline:
      - runs: |
          # The helm chart expects the binaries to be in / instead of /usr/bin
          mkdir -p "${{targets.subpkgdir}}"
          ln -sf /usr/bin/otelcol-contrib ${{targets.subpkgdir}}/otelcol-contrib

update:
  enabled: true
  github:
    identifier: open-telemetry/opentelemetry-collector-contrib
    strip-prefix: v
