package:
  name: parallel
  version: "20240222"
  epoch: 0
  description: "GNU parallel is a shell tool for executing jobs in parallel using one or more computers"
  copyright:
    - license: GPL-3.0-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - perl

pipeline:
  - uses: fetch
    with:
      uri: https://ftp.gnu.org/gnu/parallel/parallel-${{package.version}}.tar.bz2
      expected-sha256: eba09b6a7e238f622293f7d461597f35075cb56f170d0a73148f53d259ec8556

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 5448
