package:
  name: pixi
  version: 0.15.2
  epoch: 0
  description: "Package management made easy"
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - openssl-dev
      - rust
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/prefix-dev/pixi
      expected-commit: bbf4d0c19e25b461d0ba262ee5243a2b136e710b
      tag: v${{package.version}}

  - name: Configure and build
    runs: |
      cargo build --release
      mkdir -p ${{targets.destdir}}/usr/bin/
      mv target/release/pixi ${{targets.destdir}}/usr/bin/

  - uses: strip

update:
  enabled: true
  github:
    identifier: prefix-dev/pixi
    strip-prefix: v
