package:
  name: pixman
  version: 0.43.4
  epoch: 0
  description: Low-level pixel manipulation library
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - libpng-dev
      - meson

pipeline:
  - uses: fetch
    with:
      expected-sha256: 48d8539f35488d694a2fef3ce17394d1153ed4e71c05d1e621904d574be5df19
      uri: https://www.x.org/releases/individual/lib/pixman-${{package.version}}.tar.xz

  - runs: |
      export LDFLAGS="$LDFLAGS -Wl,-z,stack-size=2097152"
      meson . output --prefix=/usr \
        -Db_lto=true \
        -Ddefault_library=both

  - uses: meson/compile

  - uses: meson/install

  - uses: strip

subpackages:
  - name: pixman-static
    pipeline:
      - uses: split/static
    description: pixman static

  - name: pixman-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - pixman
    description: pixman dev

update:
  enabled: true
  release-monitor:
    identifier: 3648
