package:
  name: pombump
  version: 0.0.10
  epoch: 0
  description: Go tool for bumping versions in pom.xml files
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/chainguard-dev/pombump.git
      tag: v${{package.version}}
      expected-commit: 25249008fd8205e5d011ce09d37f7e18718a6051

  - uses: go/build
    with:
      packages: .
      output: pombump

  - uses: strip

update:
  enabled: true
  github:
    identifier: chainguard-dev/pombump
    strip-prefix: v
    use-tag: true

test:
  pipeline:
    - runs: |
        pombump version
