package:
  name: pombump
  version: 0.0.9
  epoch: 0
  description: Go tool for bumping versions in pom.xml files
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/chainguard-dev/pombump.git
      tag: v${{package.version}}
      expected-commit: c18f3617e009085e8479eabecf9bbeca9f2df781

  - uses: go/build
    with:
      packages: .
      output: pombump

  - uses: strip

update:
  enabled: true
  github:
    identifier: chainguard-dev/pombump
    strip-prefix: v
    use-tag: true

test:
  environment:
    contents:
      packages:
        - wolfi-base
  pipeline:
    - runs: |
        pombump version
