package:
  name: procps
  version: 4.0.1
  epoch: 0
  description: "utilities for monitor processes on a system"
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: GPL-2.0-or-later AND LGPL-2.1-or-later
environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - ncurses-dev
pipeline:
  - uses: fetch
    with:
      uri: https://downloads.sourceforge.net/project/procps-ng/Production/procps-ng-4.0.0.tar.xz
      expected-sha256: 0f4d92794edb7a1c95bb3b8c1f823de62be5d0043459c2155fd07fa859c16513
  - runs: |
      env FORCE_UNSAFE_CONFIGURE=1 ./configure \
         --prefix=/usr \
         --libexecdir=/usr/libexec \
         --sysconfdir=/etc \
         --mandir=/usr/share/man \
         --docdir=/usr/share/doc/procps \
         --infodir=/usr/share/info \
         --disable-nls
  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip
subpackages:
  - name: "procps-doc"
    description: "procps documentation"
    pipeline:
      - uses: split/manpages
      - uses: split/infodir
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share
          mv "${{targets.destdir}}"/usr/share/doc "${{targets.subpkgdir}}"/usr/share/
  - name: "procps-dev"
    description: "libproc development headers"
    pipeline:
      - uses: split/dev
  - name: "libproc-2-0"
    description: "libproc runtime"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/libproc*.so.* "${{targets.subpkgdir}}"/usr/lib/
