package:
  name: py3-glom
  version: 23.5.0
  epoch: 1
  description: "Python's nested data operator (and CLI), for all your declarative restructuring needs. Got data? Glom it!"
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - py3-attrs
      - py3-boltons
      - py3-face
      - python3

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - py3-gpep517
      - py3-importlib-metadata
      - py3-setuptools
      - py3-wheel
      - python3
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/g/glom/glom-${{package.version}}.tar.gz
      expected-sha256: 06af5e3486aacc59382ba34e53ebeabd7a9345d78f7dbcbee26f03baa4b83bac

  - runs: |
      python3 -m gpep517 build-wheel \
        --wheel-dir dist \
        --output-fd 3 3>&1 >&2
      python3 -m installer \
        -d "${{targets.destdir}}" \
        dist/glom-${{package.version}}-*.whl

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 120576

test:
  pipeline:
    - uses: python/import
      with:
        import: glom
