package:
  name: py3-escapism
  version: 1.0.1
  epoch: 0
  description: Simple, generic API for escaping strings.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python-3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python-3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 29e4604e1419d1b347ec1ada5d8a84af865953b0
      repository: https://github.com/minrk/escapism
      tag: ${{package.version}}

  - name: Python Build
    uses: python/build-wheel

  - uses: strip

update:
  enabled: true
  manual: false
  github:
    identifier: minrk/escapism
    use-tag: true

test:
  environment:
    contents:
      packages:
        - busybox
  pipeline:
    - runs: |
        LIBRARY="escapism"
        IMPORT_STATEMENT="import escapism"

        if ! python -c "$IMPORT_STATEMENT"; then
            echo "Failed to import library '$LIBRARY'."
            python -c "$IMPORT_STATEMENT" 2>&1
            exit 1
        else
            echo "Library '$LIBRARY' is installed and can be imported successfully."
            exit 0
        fi
