package:
  name: py3-cachetools
  version: 5.4.0
  epoch: 0
  description: Extensible memoizing collections and decorators
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/tkem/cachetools/
      tag: v${{package.version}}
      expected-commit: 990665be51af3ae879136709e8846e61d7c0e12e

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: tkem/cachetools
    strip-prefix: v
    use-tag: true

test:
  pipeline:
    - runs: |
        LIBRARY="cachetools"
        IMPORT_STATEMENT="from cachetools import TTLCache"

        if ! python -c "$IMPORT_STATEMENT"; then
            echo "Failed to import library '$LIBRARY'."
            python -c "$IMPORT_STATEMENT" 2>&1
            exit 1
        else
            echo "Library '$LIBRARY' is installed and can be imported successfully."
            exit 0
        fi
