package:
  name: py3-extras
  version: 1.0.0
  epoch: 0
  description: Useful extra bits for Python - things that shold be in the standard library
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python-3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - python-3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      expected-commit: e3b5a1b7bd0510a8bdd1cc0cf7933df28012d147
      repository: https://github.com/testing-cabal/extras
      tag: ${{package.version}}

  - name: Python Build
    uses: python/build-wheel

  - uses: strip

update:
  enabled: true
  manual: false
  github:
    identifier: testing-cabal/extras

test:
  pipeline:
    - uses: python/import
      with:
        import: extras
