package:
  name: py3-botocore
  version: 1.34.159
  epoch: 0
  description: The low-level, core functionality of Boto3
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - py3-dateutil
      - py3-docutils
      - py3-jmespath
      - py3-urllib3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/b/botocore/botocore-${{package.version}}.tar.gz
      expected-sha256: dc28806eb21e3c8d690c422530dff8b4b242ac033cbe98f160a9d37796c09cb1

  - runs: |
      python3 setup.py build

  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.contextdir}}" --skip-build

  # Fix permissions; this has 777 permissions by default.
  - runs: chmod -R 755 ${{targets.contextdir}}/usr/lib/python3.12/site-packages/botocore/data/ec2/2016-11-15/waiters-2.json

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 29738

test:
  pipeline:
    - runs: |
        LIBRARY="botocore"
        IMPORT_STATEMENT="import botocore"

        if ! python -c "$IMPORT_STATEMENT"; then
            echo "Failed to import library '$LIBRARY'."
            python -c "$IMPORT_STATEMENT" 2>&1
            exit 1
        else
            echo "Library '$LIBRARY' is installed and can be imported successfully."
            exit 0
        fi
