package:
  name: py3-tinydb
  version: 4.8.0
  epoch: 0
  description: A tiny, document-oriented database
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python-3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python-3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/msiemens/tinydb
      tag: v${{package.version}}
      expected-commit: 429b27a513f0ad301632379e55667dd99865fb16

  - name: Python Build
    uses: python/build-wheel

  - uses: strip

update:
  enabled: true
  github:
    identifier: msiemens/tinydb
    strip-prefix: v
    use-tag: true

test:
  pipeline:
    - runs: |
        python3 ./test.py > output.out 2>&1
        grep -E "ERROR|None" output.out && exit 1
