package:
  name: py3-cairo
  version: 1.26.0
  epoch: 0
  description: Python3 bindings for the cairo graphics library
  copyright:
    - license: LGPL-2.0-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cairo-dev
      - cmake
      - expat-dev
      - fontconfig-dev
      - freetype-dev
      - libpng-dev
      - meson
      - python3-dev
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pygobject/pycairo
      expected-commit: 1ef6ff7fa0ddaf2e13d928ce3c5dc2ad3fa89621
      tag: v${{package.version}}

  - uses: meson/configure
    with:
      opts: |
        -Db_lto=true

  - uses: meson/compile

  - uses: meson/install

  - runs: python3 -m compileall "${{targets.destdir}}"/usr/lib

  - uses: strip

subpackages:
  - name: py3-cairo-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - py3-cairo
    description: py3-cairo dev

update:
  enabled: true
  github:
    identifier: pygobject/pycairo
    strip-prefix: v

test:
  pipeline:
    - runs: |
        LIBRARY="cairo"
        IMPORT_STATEMENT="import cairo"

        if ! python -c "$IMPORT_STATEMENT"; then
            echo "Failed to import library '$LIBRARY'."
            python -c "$IMPORT_STATEMENT" 2>&1
            exit 1
        else
            echo "Library '$LIBRARY' is installed and can be imported successfully."
            exit 0
        fi
