package:
  name: py3-astroid
  version: 3.1.0
  epoch: 0
  description: A common base representation of python source code for pylint and other projects
  copyright:
    - license: LGPL-2.1-or-later
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-build
      - py3-installer
      - py3-pip
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pylint-dev/astroid
      tag: v${{package.version}}
      expected-commit: 3fb17a1af9f71ca1f97f623c2e141d32796a5a43

  - name: Python Build
    runs: python -m build

  - name: Python Install
    runs: python -m installer -d "${{targets.destdir}}/" dist/*.whl

  - uses: strip

update:
  enabled: true
  github:
    identifier: pylint-dev/astroid
    strip-prefix: v
