package:
  name: py3-appdirs
  version: 1.4.4
  epoch: 5
  description: a small python module for appdir support
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/a/appdirs/appdirs-${{package.version}}.tar.gz
      expected-sha256: 7d5d0167b2b1ba821647616af46a749d1c653740dd0d2415100fe26e27afdf41

  - runs: |
      python3 setup.py build

  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}" --skip-build

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 6278

test:
  environment:
    contents:
      packages:
        - busybox
  pipeline:
    - runs: |
        LIBRARY="appdirs"
        IMPORT_STATEMENT="import appdirs"

        if ! python -c "$IMPORT_STATEMENT"; then
            echo "Failed to import library '$LIBRARY'."
            python -c "$IMPORT_STATEMENT" 2>&1
            exit 1
        else
            echo "Library '$LIBRARY' is installed and can be imported successfully."
            exit 0
        fi
