package:
  name: py3-future
  version: 1.0.0
  epoch: 0
  description: Clean single-source support for Python 3 and 2
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/PythonCharmers/python-future
      expected-commit: 2bdbfa5664241fee622b23590abd3492f973afc9
      tag: v${{package.version}}

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: PythonCharmers/python-future
    strip-prefix: v

test:
  pipeline:
    - uses: python/import
      with:
        import: future
