package:
  name: py3-boltons
  version: 23.0.0
  epoch: 1
  description: When they're not builtins, they're boltons.
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - py3-gpep517
      - py3-setuptools
      - py3-wheel
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/mahmoud/boltons
      tag: ${{package.version}}
      expected-commit: 2adf15c735396b10e5050072babba0c319766726

  - runs: |
      python3 -m gpep517 build-wheel \
        --wheel-dir dist \
        --output-fd 3 3>&1 >&2
      python3 -m installer \
        -d "${{targets.destdir}}" \
        dist/boltons-${{package.version}}-*.whl
      install -Dm644 LICENSE \
        "${{targets.destdir}}"/usr/share/licenses/${{package.name}}/LICENSE

  - uses: strip

update:
  enabled: true
  github:
    identifier: mahmoud/boltons

test:
  pipeline:
    - runs: |
        LIBRARY="boltons"
        IMPORT_STATEMENT="import boltons"

        if ! python -c "$IMPORT_STATEMENT"; then
            echo "Failed to import library '$LIBRARY'."
            python -c "$IMPORT_STATEMENT" 2>&1
            exit 1
        else
            echo "Library '$LIBRARY' is installed and can be imported successfully."
            exit 0
        fi
