package:
  name: py3-face
  version: 22.0.0
  epoch: 2
  description: "A command-line application framework (and CLI parser). Friendly for users, full-featured for developers."
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - py3-boltons
      - python3

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - py3-gpep517
      - py3-setuptools
      - py3-wheel
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/mahmoud/face
      tag: v${{package.version}}
      expected-commit: 6c8b1070312683cca0ed723f1cb99a7307f5ee91

  - runs: |
      python3 -m gpep517 build-wheel \
        --wheel-dir dist \
        --output-fd 3 3>&1 >&2
      python3 -m installer \
        -d "${{targets.destdir}}" \
        dist/face-${{package.version}}-*.whl

  - uses: strip

update:
  enabled: true
  github:
    identifier: mahmoud/face
    strip-prefix: v
    use-tag: true

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          from face import Command, echo
