package:
  name: py3-importlib-resources
  version: 6.1.2
  epoch: 0
  description: Read resources from Python packages
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - py3-zipp
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-gpep517
      - py3-setuptools
      - py3-wheel
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/python/importlib_resources
      tag: v${{package.version}}
      expected-commit: 131906a73870c0de86e6817dd54f61b26b33db02

  - name: Python Build
    runs: |
      export SETUPTOOLS_SCM_PRETEND_VERSION=${{package.version}}
       python3 -m gpep517 build-wheel \
       --wheel-dir dist \
       --output-fd 3 3>&1 >&2

       python3 -m installer -d "${{targets.destdir}}" \
       dist/*.whl

  - uses: strip

update:
  enabled: true
  github:
    identifier: python/importlib_resources
    strip-prefix: v
    use-tag: true
