package:
  name: py3-absl-py
  version: 2.1.0
  epoch: 1
  description: Abseil Python Common Libraries, see https://github.com/abseil/abseil-py.
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/abseil/abseil-py/
      tag: v${{package.version}}
      expected-commit: 8abdd60755e5b6ebfa2b383cf6eaa0d9315335bd

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: abseil/abseil-py
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - busybox
  pipeline:
    - runs: |
        LIBRARY="absl"
        IMPORT_STATEMENT="from absl import app"

        if ! python -c "$IMPORT_STATEMENT"; then
            echo "Failed to import library '$LIBRARY'."
            python -c "$IMPORT_STATEMENT" 2>&1
            exit 1
        else
            echo "Library '$LIBRARY' is installed and can be imported successfully."
            exit 0
        fi
