package:
  name: py3-pip
  version: "24.2"
  epoch: 1
  description: The PyPA recommended tool for installing Python packages.
  copyright:
    - license: MIT
  dependencies:
    provider-priority: 0

vars:
  pypi-package: pip

data:
  - name: py-versions
    items:
      3.10: "310"
      3.11: "311"
      3.12: "312"

environment:
  contents:
    packages:
      - build-base
      - busybox
      - py3-supported-python

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pypa/pip
      expected-commit: 97146c7f4cd85551f3dc261830a57f304e43c181
      tag: ${{package.version}}

  - uses: patch
    with:
      patches: pip-urllib3-bump.patch

subpackages:
  - range: py-versions
    # Historically py3.X-pip installed /usr/bin/pip
    # Hence co-installable modules only package is called -base
    # And /usr/bin/pip conflicting package is called py3.X-pip
    name: py${{range.key}}-${{vars.pypi-package}}-base
    description: ${{vars.pypi-package}} installed for python${{range.key}}
    pipeline:
      - uses: py/pip-build-install-bootstrap
        with:
          python: python${{range.key}}
    dependencies:
      runtime:
        - py${{range.key}}-setuptools

  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: Executable binaries for ${{vars.pypi-package}} installed for python${{range.key}}
    dependencies:
      runtime:
        - py${{range.key}}-${{vars.pypi-package}}-base
      provides:
        - py3-${{vars.pypi-package}}
      provider-priority: ${{range.value}}
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/usr/bin
          mv ${{targets.contextdir}}/../py${{range.key}}-${{vars.pypi-package}}-base/usr/bin/pip ${{targets.contextdir}}/usr/bin/
          mv ${{targets.contextdir}}/../py${{range.key}}-${{vars.pypi-package}}-base/usr/bin/pip3 ${{targets.contextdir}}/usr/bin/

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.12-${{vars.pypi-package}}-base
        - py3.11-${{vars.pypi-package}}-base
        - py3.10-${{vars.pypi-package}}-base

update:
  ignore-regex-patterns:
    - b
  enabled: true
  shared: true
  github:
    identifier: pypa/pip
    use-tag: true

test:
  pipeline:
    - uses: python/import
      with:
        import: pip
