package:
  name: py3-pandas
  version: 2.2.1
  epoch: 0
  description: Powerful data structures for data analysis, time series, and statistics
  copyright:
    - license: 'BSD-3-Clause'
  dependencies:
    runtime:
      - numpy
      - py3-dateutil
      - py3-tz
      - py3-tzdata
      - python-3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cython
      - meson
      - numpy
      - py3-dateutil
      - py3-gpep517
      - py3-meson-python
      - py3-setuptools
      - py3-tz
      - py3-tzdata
      - py3-versioneer
      - py3-wheel
      - python-3
      - python-3-dev
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pandas-dev/pandas
      tag: v${{package.version}}
      expected-commit: bdc79c146c2e32f2cab629be240f01658cfb6cc2

  - runs: |
      # You have to do this dance with the FDs because without it things fail.
      # I don't know why, but other places do this, so I'm just copying them.
      python3 -m gpep517 build-wheel --wheel-dir dist --output-fd 3 3>&1 >&2
      python3 -m installer -d "${{targets.destdir}}" dist/*.whl

  - uses: strip

update:
  enabled: true
  github:
    identifier: pandas-dev/pandas
    strip-prefix: v
