package:
  name: py3-codespell
  version: 2.2.6
  epoch: 0
  description: 'checker for common misspellings '
  copyright:
    - license: GPL-2.0-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-pip
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/codespell-project/codespell
      tag: v${{package.version}}
      expected-commit: 6e41aba91fb32e9feb741a6258eefeb9c6e4a482

  - name: Python Build
    uses: python/build-wheel

  - uses: strip

update:
  enabled: true
  github:
    identifier: codespell-project/codespell
    strip-prefix: v
