package:
  name: py3-defusedxml
  version: 0.7.1
  epoch: 1
  description: XML bomb protection for Python stdlib modules
  copyright:
    - license: PSF-2.0
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - py3-gpep517
      - py3-setuptools
      - py3-wheel
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/tiran/defusedxml
      tag: v${{package.version}}
      expected-commit: ebff1b493751e2f0775314bdd4188d64f07ea184

  - runs: |
      python3 -m gpep517 build-wheel \
        --wheel-dir dist \
        --output-fd 3 3>&1 >&2
      python3 -m installer \
        -d "${{targets.destdir}}" \
        dist/defusedxml-${{package.version}}-*.whl
      install -Dm644 LICENSE \
        "${{targets.destdir}}"/usr/share/licenses/${{package.name}}/LICENSE

  - uses: strip

update:
  enabled: true
  github:
    identifier: tiran/defusedxml
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - busybox
  pipeline:
    - runs: |
        LIBRARY="defusedxml"
        IMPORT_STATEMENT="import defusedxml"

        if ! python -c "$IMPORT_STATEMENT"; then
            echo "Failed to import library '$LIBRARY'."
            python -c "$IMPORT_STATEMENT" 2>&1
            exit 1
        else
            echo "Library '$LIBRARY' is installed and can be imported successfully."
            exit 0
        fi
