package:
  name: py3-argcomplete
  version: 3.2.2
  epoch: 0
  description: Bash/zsh tab completion for argparse
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - python-3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 2a6c23bcc8b1d389938a2f7db2d12d449d1ac512
      repository: https://github.com/kislyuk/argcomplete
      tag: v${{package.version}}

  - name: Python Build
    uses: python/build-wheel

  - uses: strip

update:
  enabled: true
  github:
    identifier: kislyuk/argcomplete
    strip-prefix: v

test:
  pipeline:
    - runs: |
        LIBRARY="argcomplete"
        IMPORT_STATEMENT="import argcomplete"

        if ! python -c "$IMPORT_STATEMENT"; then
            echo "Failed to import library '$LIBRARY'."
            python -c "$IMPORT_STATEMENT" 2>&1
            exit 1
        else
            echo "Library '$LIBRARY' is installed and can be imported successfully."
            exit 0
        fi
