package:
  name: py3-cloudpickle
  version: 3.0.0
  epoch: 1
  description: Extended pickling support for Python objects
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-flit-core
      - py3-gpep517
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/cloudpipe/cloudpickle
      expected-commit: 227f24668b97b15e627e9a3e1e3bec526b101f5c
      tag: v${{package.version}}

  - name: Python Build
    uses: python/build-wheel

  - uses: strip

update:
  ignore-regex-patterns:
    - ^\.
  enabled: true
  github:
    identifier: cloudpipe/cloudpickle
    strip-prefix: v
    use-tag: true
    tag-filter: v

test:
  pipeline:
    - runs: |
        LIBRARY="cloudpickle"
        IMPORT_STATEMENT="import cloudpickle"

        if ! python -c "$IMPORT_STATEMENT"; then
            echo "Failed to import library '$LIBRARY'."
            python -c "$IMPORT_STATEMENT" 2>&1
            exit 1
        else
            echo "Library '$LIBRARY' is installed and can be imported successfully."
            exit 0
        fi
