package:
  name: py3-influxdb-client
  version: 1.45.0
  epoch: 0
  description: "InfluxDB 2.0 python client"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-certifi
      - py3-dateutil
      - py3-pip
      - py3-setuptools
      - py3-urllib3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/influxdata/influxdb-client-python.git
      tag: v${{package.version}}
      expected-commit: db1630d52ecd29f2f1008ca25c742fa26ee3777c

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: influxdata/influxdb-client-python
    strip-prefix: v
    use-tag: true
