package:
  name: py3-gpep517
  version: 11
  epoch: 0
  description: "PEP517 build system support for distros"
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: MIT
  dependencies:
    runtime:
      - python3
      - py3-installer
      - py3-tomli
environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - python3
pipeline:
  - uses: fetch
    with:
      uri: https://github.com/mgorny/gpep517/archive/v${{package.version}}/gpep517-v${{package.version}}.tar.gz
      expected-sha256: 0e59a42d67d40a5d5a1c35345e1ca3bedab0260c3b1d395ed05ded3af65b0699
  - runs: |
      _site_pkgs="$(python3 -c 'import site; print(site.getsitepackages()[0])')"
      _py3ver=$(python3 -c 'import sys; print("{}.{}".format(sys.version_info.major, sys.version_info.minor))')

      mkdir -p "${{targets.destdir}}"/"$_site_pkgs"
      cp -a gpep517 "${{targets.destdir}}"/$_site_pkgs/
  - uses: strip
