package:
  name: py3-bracex
  version: '2.4'
  epoch: 1
  description: Bash style brace expander.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - py3-gpep517
      - py3-pip
      - py3-setuptools
      - py3-wheel
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/facelessuser/bracex
      tag: ${{package.version}}
      expected-commit: 9c9e5465f1a6d6e40763c9a2501b47a039909c30

  - runs: |
      # This is needed to work around the error "ValueError: ZIP does not support timestamps before 1980"
      export SOURCE_DATE_EPOCH=315532800
      python3 -m pip install -U hatchling
      python3 -m gpep517 build-wheel \
        --wheel-dir dist \
        --output-fd 3 3>&1 >&2
      python3 -m installer \
        -d "${{targets.destdir}}" \
        dist/bracex-${{package.version}}-*.whl
      install -Dm644 LICENSE.md \
        "${{targets.destdir}}"/usr/share/licenses/${{package.name}}/LICENSE

  - uses: strip

update:
  enabled: true
  github:
    identifier: facelessuser/bracex
    strip-suffix: .post1

test:
  environment:
    contents:
      packages:
        - busybox
  pipeline:
    - runs: |
        LIBRARY="bracex"
        IMPORT_STATEMENT="import bracex"

        if ! python -c "$IMPORT_STATEMENT"; then
            echo "Failed to import library '$LIBRARY'."
            python -c "$IMPORT_STATEMENT" 2>&1
            exit 1
        else
            echo "Library '$LIBRARY' is installed and can be imported successfully."
            exit 0
        fi
