package:
  name: py3-asn1crypto
  version: 1.5.1
  epoch: 0
  description: Python ASN.1 library with a focus on performance and a pythonic API
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/wbond/asn1crypto
      expected-commit: 835365ca6744c7afee793f050faf0a91ddb140b7
      tag: ${{package.version}}

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: wbond/asn1crypto
    strip-prefix: v
    use-tag: true

test:
  pipeline:
    - runs: |
        LIBRARY="asn1crypto"
        IMPORT_STATEMENT="from asn1crypto import cms"

        if ! python -c "$IMPORT_STATEMENT"; then
            echo "Failed to import library '$LIBRARY'."
            python -c "$IMPORT_STATEMENT" 2>&1
            exit 1
        else
            echo "Library '$LIBRARY' is installed and can be imported successfully."
            exit 0
        fi
