package:
  name: py3-asn1
  version: 0.4.8
  epoch: 6
  description: Python3 ASN1 library
  copyright:
    - license: BSD-2-Clause
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/p/pyasn1/pyasn1-${{package.version}}.tar.gz
      expected-sha256: aef77c9fb94a3ac588e87841208bdec464471d9871bd5050a287cc9a475cd0ba

  - runs: |
      python3 setup.py build

  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}" --skip-build

  - uses: strip

update:
  enabled: true
  github:
    identifier: etingof/pyasn1
    strip-prefix: v
