package:
  name: py3-alabaster
  version: 0.7.16
  epoch: 0
  description: A configurable sidebar-enabled Sphinx theme
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/bitprophet/alabaster
      expected-commit: f3fdc049e4b531595bc075718a66677fbca851e3
      tag: ${{package.version}}

  - name: Python Build
    uses: python/build-wheel

  - uses: strip

update:
  enabled: true
  github:
    identifier: bitprophet/alabaster

test:
  pipeline:
    - runs: |
        LIBRARY="alabaster"
        IMPORT_STATEMENT="import alabaster"

        if ! python -c "$IMPORT_STATEMENT"; then
            echo "Failed to import library '$LIBRARY'."
            python -c "$IMPORT_STATEMENT" 2>&1
            exit 1
        else
            echo "Library '$LIBRARY' is installed and can be imported successfully."
            exit 0
        fi
