package:
  name: py3-pip
  version: 22.3.1
  epoch: 0
  description: "tool for installing and managing python packages"
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: MIT
  dependencies:
    runtime:
      - python3
      - py3-contextlib2
      - py3-pep517
      - py3-retrying
      - py3-setuptools
environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - python3
      - py3-contextlib2
      - py3-pep517
      - py3-retrying
      - py3-setuptools
pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/p/pip/pip-${{package.version}}.tar.gz
      expected-sha256: 65fd48317359f3af8e593943e6ae1506b66325085ea64b706a998c6e83eeaf38
  - runs: |
      python3 setup.py build
  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}"
  - uses: strip
