package:
  name: py3-jinja2
  version: 3.1.3
  epoch: 1
  description: "A small but fast and easy to use stand-alone python template engine"
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - py3-markupsafe

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3-dev
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/J/Jinja2/Jinja2-${{package.version}}.tar.gz
      expected-sha512: 5c36d0cd094b40626511f30c561176c095c49ef4066c2752a9edc3e6feb2430dafa866c17deebddcd0168aa1f0fd3944916d592c5c999639b8152e7c1009c700

  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}"

      docdir="/usr/share/doc/${{package.name}}"
      # Note: The documentation in the docs directory needs to be generated
      # by py-sphinx, however, this package (py-jinja2) is a dependency of
      # Sphinx itself!
      mkdir -p "$docdir"
      cp -R docs examples "$docdir"/

      install -m 644 -D LICENSE.rst /usr/share/licenses/${{package.name}}/LICENSE.rst

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 3894

test:
  pipeline:
    - runs: python -c 'import jinja2'
