package:
  name: py3-astunparse
  version: 1.6.3
  epoch: 3
  description: An AST unparser for Python
  copyright:
    - license: BSD-3-Clause
  dependencies:
    provider-priority: 0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - py3-supported-pip
      - py3-supported-python
      - py3-supported-setuptools
      - py3-supported-wheel

vars:
  pypi-package: astunparse

data:
  - name: py-versions
    items:
      3.10: "310"
      3.11: "311"
      3.12: "312"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/simonpercivall/astunparse
      tag: v${{package.version}}
      expected-commit: 2acce01fcdda2ea32eea835c30ccca21aaff7297

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: ${{vars.pypi-package}} installed for python${{range.key}}
    dependencies:
      runtime:
        - py${{range.key}}-six
      provides:
        - py3-${{vars.pypi-package}}
      provider-priority: ${{range.value}}
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            import: ${{vars.pypi-package}}

update:
  enabled: true
  github:
    identifier: simonpercivall/astunparse
    strip-prefix: v
    use-tag: true
