package:
  name: py3-charset-normalizer
  version: 3.3.2
  epoch: 5
  description: "offers you an alternative to Universal Charset Encoding Detector, also known as Chardet"
  copyright:
    - license: MIT
  dependencies:
    provider-priority: 0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - py3-supported-pip
      - py3-supported-python
      - py3-supported-setuptools
      - py3-supported-wheel

vars:
  pypi-package: charset-normalizer
  module-name: charset_normalizer

data:
  - name: py-versions
    items:
      3.10: "310"
      3.11: "311"
      3.12: "312"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/jawah/charset_normalizer.git
      tag: ${{package.version}}
      expected-commit: 79dce4857914fead2ffe55eb787cad6d5cf14643

  - runs: |
      sed -i '/cov-report/d' setup.cfg

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: ${{vars.pypi-package}} installed for python${{range.key}}
    dependencies:
      provides:
        - py3-${{vars.pypi-package}}
      provider-priority: ${{range.value}}
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            import: ${{vars.module-name}}

update:
  enabled: true
  github:
    identifier: jawah/charset_normalizer
