package:
  name: py3-colorama
  version: 0.4.6
  epoch: 3
  description: Simple cross-platform colored terminal text
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-gpep517
      - py3-hatchling
      - py3-packaging
      - py3-pathspec
      - py3-pluggy
      - py3-setuptools
      - py3-trove-classifiers
      - python3
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/tartley/colorama/archive/${{package.version}}.tar.gz
      expected-sha512: 2b269b190041398a1808b0b5147e47422b4451a1bc91841d0957572214ba8addd731c8932afdc60bfbba9833a0fe6c9c5c2ecb150613f13498f661799d625e4f

  - runs: |
      # workaround for issue: ZIP does not support timestamps before 1980
      unset SOURCE_DATE_EPOCH
      backend="$(python3 -m gpep517 get-backend)"
      python3 -m gpep517 build-wheel --wheel-dir dist --backend "$backend" --output-fd 1

  - runs: |
      echo here here
      python3 -m installer -d "${{targets.destdir}}" dist/colorama*.whl
      rm -r "${{targets.destdir}}"/usr/lib/python3*/site-packages/colorama/tests

  - uses: strip

update:
  enabled: true
  github:
    identifier: tartley/colorama
    use-tag: true

test:
  pipeline:
    - runs: |
        LIBRARY="colorama"
        IMPORT_STATEMENT="import colorama"

        if ! python -c "$IMPORT_STATEMENT"; then
            echo "Failed to import library '$LIBRARY'."
            python -c "$IMPORT_STATEMENT" 2>&1
            exit 1
        else
            echo "Library '$LIBRARY' is installed and can be imported successfully."
            exit 0
        fi
