package:
  name: py3.10-setuptools
  version: 69.1.1
  epoch: 0
  description: Easily download, build, install, upgrade, and uninstall Python packages
  copyright:
    - license: "MIT"
  dependencies:
    runtime:
      - python-3.10

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - python-3.10
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      expected-sha256: 5c0806c7d9af348e6dd3777b4f4dbb42c7ad85b190104837488eab9a7c945cf8
      uri: https://files.pythonhosted.org/packages/source/s/setuptools/setuptools-${{package.version}}.tar.gz

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  shared: true
  release-monitor:
    identifier: 4021
