package:
  name: python-3.10
  version: 3.10.13
  epoch: 4
  description: "the Python programming language"
  copyright:
    - license: PSF-2.0
  dependencies:
    provides:
      - python3=${{package.full-version}}
      - python-3=${{package.full-version}}

environment:
  contents:
    packages:
      - build-base
      - busybox
      - bzip2-dev
      - ca-certificates-bundle
      - expat-dev
      - gdbm-dev
      - libffi-dev
      - linux-headers
      - mpdecimal-dev
      - ncurses-dev
      - openssl-dev
      - readline-dev
      - sqlite-dev
      - xz-dev
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      uri: https://www.python.org/ftp/python/${{package.version}}/Python-${{package.version}}.tar.xz
      expected-sha256: 5c88848668640d3e152b35b4536ef1c23b2ca4bd2c957ef1ecbb053f571dd3f6

  - name: Force use of system libraries
    runs: |
      rm -rf Modules/expat \
        Modules/_ctypes/darwin* \
        Modules/_ctypes/libffi*

  - name: Configure
    runs: |
      ./configure \
         --host=${{host.triplet.gnu}} \
         --build=${{host.triplet.gnu}} \
         --target=${{host.triplet.gnu}} \
         --prefix=/usr \
         --enable-ipv6 \
         --enable-loadable-sqlite-extensions \
         --enable-optimizations \
         --enable-shared \
         --without-lto \
         --with-computed-gotos \
         --with-dbmliborder=gdbm:ndbm \
         --with-system-expat \
         --with-system-ffi \
         --with-system-libmpdec \
         --without-ensurepip \
         --with-lto

  - uses: autoconf/make

  - uses: autoconf/make
    with:
      opts: altinstall DESTDIR="${{targets.destdir}}"

  - runs: |
      find ${{targets.destdir}}/usr/lib -type f -name '*.pyc' -exec rm -rf '{}' +
      find ${{targets.destdir}}/usr/lib -type f -name '*.pyo' -exec rm -rf '{}' +
      find ${{targets.destdir}}/usr/lib -type f -name 'libpython*.a' -exec rm -rf '{}' +
      find ${{targets.destdir}}/usr/lib -type d -name 'test' -exec rm -rf '{}' +
      find ${{targets.destdir}}/usr/lib -type d -name 'tests' -exec rm -rf '{}' +
      find ${{targets.destdir}}/usr/lib -type d -name 'idle_test' -exec rm -rf '{}' +

  - name: Install python symlink
    runs: |
      ln -s python3.10 "${{targets.destdir}}"/usr/bin/python
      ln -s python3.10 "${{targets.destdir}}"/usr/bin/python3

  - uses: strip

subpackages:
  - name: "python-3.10-doc"
    description: "python3.10 documentation"
    pipeline:
      - uses: split/manpages

  - name: "python-3.10-dev"
    description: "python3.10 development headers"
    pipeline:
      - uses: split/dev
      - runs: |
          mkdir -p "${{targets.destdir}}"/usr/include/python3.10
          mv "${{targets.subpkgdir}}"/usr/include/python3.10/pyconfig.h "${{targets.destdir}}"/usr/include/python3.10
    dependencies:
      provides:
        - python3-dev=${{package.full-version}}
        - python-3-dev=${{package.full-version}}

update:
  enabled: true
  shared: true
  github:
    identifier: python/cpython
    strip-prefix: v
    tag-filter: v3.10
    use-tag: true

test:
  environment:
    contents:
      packages:
        - wolfi-base
  pipeline:
    - runs: |
        python3 --version
