package:
  name: python3
  version: 3.11.0
  epoch: 0
  description: "the Python programming language"
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: PSF-2.0
  dependencies:
    runtime:
secfixes:
  3.0.7-r0:
    - CVE-2020-10735
environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/bootstrap/stage3
    keyring:
      - https://packages.wolfi.dev/bootstrap/stage3/wolfi-signing.rsa.pub
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - bzip2-dev
      - expat-dev
      - gdbm-dev
      - libffi-dev
      - linux-headers
      - mpdecimal-dev
      - ncurses-dev
      - openssl-dev
      - readline-dev
      - sqlite-dev
      - xz-dev
      - zlib-dev
pipeline:
  - uses: fetch
    with:
      uri: https://www.python.org/ftp/python/${{package.version}}/Python-${{package.version}}.tar.xz
      expected-sha256: a57dc82d77358617ba65b9841cee1e3b441f386c3789ddc0676eca077f2951c3
  - name: Force use of system libraries
    runs: |
      rm -rf Modules/expat \
        Modules/_ctypes/darwin* \
        Modules/_ctypes/libffi*
  - name: Configure
    runs: |
      ./configure \
         --host=${{host.triplet.gnu}} \
         --build=${{host.triplet.gnu}} \
         --target=${{host.triplet.gnu}} \
         --prefix=/usr \
         --enable-ipv6 \
         --enable-loadable-sqlite-extensions \
         --enable-optimizations \
         --enable-shared \
         --without-lto \
         --with-computed-gotos \
         --with-dbmliborder=gdbm:ndbm \
         --with-system-expat \
         --with-system-ffi \
         --with-system-libmpdec \
         --without-ensurepip
  - uses: autoconf/make
  - uses: autoconf/make-install
  - name: Install python symlink
    runs: |
      ln -s python3 "${{targets.destdir}}"/usr/bin/python
  - uses: strip
subpackages:
  - name: "python3-doc"
    description: "python3 documentation"
    pipeline:
      - uses: split/manpages
  - name: "python3-dev"
    description: "python3 development headers"
    pipeline:
      - uses: split/dev
      # pyconfig.h is needed at runtime... ugh.
      - runs: |
          mkdir -p "${{targets.destdir}}"/usr/include/python3.10
          mv "${{targets.subpkgdir}}"/usr/include/python3.10/pyconfig.h "${{targets.destdir}}"/usr/include/python3.10
    dependencies:
      runtime:
        - python3
