package:
  name: python-3.11
  version: 3.11.8
  epoch: 1
  description: "the Python programming language"
  copyright:
    - license: PSF-2.0
  dependencies:
    provides:
      - python3=3.11.999
      - python-3=3.11.999

environment:
  contents:
    packages:
      - build-base
      - busybox
      - bzip2-dev
      - ca-certificates-bundle
      - expat-dev
      - gdbm-dev
      - libffi-dev
      - linux-headers
      - mpdecimal-dev
      - ncurses-dev
      - openssl-dev
      - readline-dev
      - sqlite-dev
      - xz-dev
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      uri: https://www.python.org/ftp/python/${{package.version}}/Python-${{package.version}}.tar.xz
      expected-sha256: 9e06008c8901924395bc1da303eac567a729ae012baa182ab39269f650383bb3

  - name: Force use of system libraries
    runs: |
      rm -rf Modules/expat \
        Modules/_ctypes/darwin* \
        Modules/_ctypes/libffi*

  - uses: patch
    with:
      patches: CVE-2023-27043.patch

  - uses: patch
    with:
      patches: CVE-2023-27043-enable-disable.patch

  - name: Configure
    runs: |
      ./configure \
         --host=${{host.triplet.gnu}} \
         --build=${{host.triplet.gnu}} \
         --target=${{host.triplet.gnu}} \
         --prefix=/usr \
         --enable-ipv6 \
         --enable-loadable-sqlite-extensions \
         --enable-optimizations \
         --enable-shared \
         --without-lto \
         --with-computed-gotos \
         --with-dbmliborder=gdbm:ndbm \
         --with-system-expat \
         --with-system-ffi \
         --with-system-libmpdec \
         --without-ensurepip \
         --with-lto

  - uses: autoconf/make

  - uses: autoconf/make-install

  - runs: |
      find ${{targets.destdir}}/usr/lib -type f -name '*.pyc' -exec rm -rf '{}' +
      find ${{targets.destdir}}/usr/lib -type f -name '*.pyo' -exec rm -rf '{}' +
      find ${{targets.destdir}}/usr/lib -type f -name 'libpython*.a' -exec rm -rf '{}' +
      find ${{targets.destdir}}/usr/lib -type d -name 'test' -exec rm -rf '{}' +
      find ${{targets.destdir}}/usr/lib -type d -name 'tests' -exec rm -rf '{}' +
      find ${{targets.destdir}}/usr/lib -type d -name 'idle_test' -exec rm -rf '{}' +

  - name: Install python symlink
    runs: |
      ln -s python3 "${{targets.destdir}}"/usr/bin/python

  - uses: strip

test:
  pipeline:
    - runs: |
        python3.11 CVE-2023-27043-unittest.py

subpackages:
  - name: "python-3.11-doc"
    description: "python3 documentation"
    pipeline:
      - uses: split/manpages

  - name: "python-3.11-dev"
    description: "python3 development headers"
    pipeline:
      - uses: split/dev
      - runs: |
          # pyconfig.h is needed at runtime... ugh.
          mkdir -p "${{targets.destdir}}"/usr/include/python3.11
          mv "${{targets.subpkgdir}}"/usr/include/python3.11/pyconfig.h "${{targets.destdir}}"/usr/include/python3.11
    dependencies:
      provides:
        - python3-dev=3.11.999
        - python-3-dev=3.11.999

update:
  enabled: true
  shared: true
  github:
    identifier: python/cpython
    strip-prefix: v
    tag-filter: v3.11
    use-tag: true
