package:
  name: qpdf
  version: 11.9.0
  epoch: 0
  description: Command-line tools and library for transforming PDF files
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - gnutls-dev
      - libjpeg-turbo-dev
      - openssl-dev
      - samurai
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/qpdf/qpdf
      tag: v${{package.version}}
      expected-commit: 3b97c9bd266b7c32ea36d3536e22dab77412886d

  - name: Build
    runs: |
      cmake -B build -G Ninja \
      	-DCMAKE_INSTALL_PREFIX=/usr \
      	-DCMAKE_BUILD_TYPE=MinSizeRel \
      	-DBUILD_STATIC_LIBS=OFF \
      	-DBUILD_DOC_PDF=OFF \
      	-DBUILD_DOC_HTML=OFF \
      	-DINSTALL_EXAMPLES=OFF
      cmake --build build

  - name: Package
    runs: DESTDIR="${{targets.destdir}}" cmake --install build

  - uses: strip

subpackages:
  - name: qpdf-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - qpdf
    description: qpdf dev

  - name: qpdf-doc
    pipeline:
      - uses: split/manpages
    description: qpdf manpages

  - name: qpdf-fix-qdf
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/fix-qdf "${{targets.subpkgdir}}"/usr/bin/
    description: Repair PDF files in QDF form after editing

test:
  environment:
    contents:
      packages:
        - wolfi-base
  pipeline:
    - runs: |
        qpdf -version

update:
  enabled: true
  ignore-regex-patterns:
    - "release-qpdf*"
  github:
    identifier: qpdf/qpdf
    strip-prefix: v
