package:
  name: rook
  version: 1.13.5
  epoch: 0
  description: Storage Orchestration for Kubernetes
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/rook/rook
      expected-commit: b09a653e947c0426f3c8c954e5a8a52c903f0b3d
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.17.0

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin/
      go build \
        -ldflags="-X 'github.com/rook/rook/pkg/version.Version=${{package.version}}'" \
        -o ${{targets.destdir}}/usr/bin/rook \
        ./cmd/rook

  - runs: |
      mv images/ceph/toolbox.sh ${{targets.destdir}}/usr/bin/

      mkdir -p ${{targets.destdir}}/etc/rook-external
      mv deploy/examples/create-external-cluster-resources.* ${{targets.destdir}}/etc/rook-external

      mv build/csv ${{targets.destdir}}/etc/ceph-csv-templates

      mv deploy/examples/monitoring ${{targets.destdir}}/etc/ceph-monitoring

  - uses: strip

subpackages:
  - name: rook-oci-compat
    dependencies:
      runtime:
        - rook
        - s5cmd
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/local/bin
          ln -sf /usr/bin/rook ${{targets.subpkgdir}}/usr/local/bin/rook
    test:
      environment:
        contents:
          packages:
            - wolfi-base
      pipeline:
        - runs: |
            rook version

update:
  enabled: true
  github:
    identifier: rook/rook
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - wolfi-base
  pipeline:
    - runs: |
        rook version
