package:
  name: rstudio
  version: 2023.12.0_p369
  epoch: 1
  description: RStudio is an integrated development environment (IDE) for R
  copyright:
    - license: GPL-3.0-or-later
  dependencies:
    runtime:
      - R
      - bash
      - esbuild
      - nodejs

var-transforms:
  - from: ${{package.version}}
    match: _p
    replace: +
    to: mangled-package-version

environment:
  contents:
    packages:
      - R
      - R-dev
      - R-doc
      - R-mathlib
      - ant
      - autoconf
      - automake
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - libuuid
      - linux-pam-dev
      - nodejs
      - openjdk-8-default-jdk
      - openssl-dev
      - posix-libc-utils
      - sqlite-dev
      - util-linux-dev
      - wget
      - yaml-cpp
      - yaml-cpp-dev
      - yarn
      - zlib-dev
  environment:
    LANG: en_US.UTF-8
    JAVA_HOME: /usr/lib/jvm/java-1.8-openjdk

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/rstudio/rstudio
      expected-commit: 960e8fa44552e2c0e917260463dfec48c83f215c
      tag: v${{vars.mangled-package-version}}

  - uses: patch
    with:
      # rstudio attempts to vendor it's own node, let's use ours instead.
      patches: node.patch

  - runs: |
      cd dependencies/common
      ./install-dictionaries
      ./install-mathjax
      ./install-quarto
      ./install-boost
      ./install-soci
      ./install-panmirror

  - uses: cmake/configure
    with:
      opts: |
        -DRSTUDIO_TARGET=Server \
        -DCMAKE_BUILD_TYPE=Release \
        -DRSTUDIO_USE_SYSTEM_YAML_CPP=true

  - uses: cmake/build

  - uses: cmake/install

  - runs: |
      # quarto includes its own esbuild. drop that to use ours
      rm ${{targets.destdir}}/usr/bin/quarto/bin/tools/esbuild
      ln -sf /usr/bin/esbuild ${{targets.destdir}}/usr/bin/quarto/bin/tools/esbuild

  - uses: strip

update:
  # Doesn't work with the tagging scheme.
  enabled: false
  github:
    identifier: rstudio/rstudio
    use-tag: true
    strip-prefix: v

test:
  pipeline:
    - runs: |
        rstudio-server version
