#nolint:valid-pipeline-git-checkout-tag
package:
  name: ruby3.2-aws-eventstream
  version: 1.3.1_git20241011
  epoch: 0
  description: Amazon Web Services event stream library. Decodes and encodes binary stream under `vnd.amazon.event-stream` content-type
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 0a2be0d095b7a70cacb08c8631fe9a31275c617d
      repository: https://github.com/aws/aws-sdk-ruby
      branch: version-3

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}
      dir: gems/${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}
      dir: gems/${{vars.gem}}

  - uses: ruby/clean

vars:
  gem: aws-eventstream

update:
  enabled: true
  git: {}
  schedule:
    period: daily
    reason: upstream project uses a rolling release model with a branch
