package:
  name: ruby3.2-jrjackson
  version: 0.4.18
  epoch: 3
  description: A mostly native JRuby wrapper for the java jackson json processor jar
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - jruby-9.4
      - jruby-9.4-default-ruby
      - openjdk-8-default-jdk # build with JDK 8 since this is the declared version in the upstream Mavenfile
  environment:
    JAVA_HOME: /usr/lib/jvm/java-1.8-openjdk

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 86e21566467349cb92ee5687f2933335ee227c93
      repository: https://github.com/guyboertje/jrjackson
      tag: v${{package.version}}

  - uses: patch
    with:
      patches: mavenfile.patch

  - runs: |
      bundle install
      bundle exec rake
      rake test

  - runs: |
      jruby -S gem build ${{vars.gem}}.gemspec

  - uses: ruby/install
    with:
      # Output file name has `java` suffix.
      gem-file: ${{vars.gem}}-${{package.version}}-java.gem
      version: ${{package.version}}

  - uses: ruby/clean

vars:
  gem: jrjackson

update:
  enabled: true
  github:
    identifier: guyboertje/jrjackson
    strip-prefix: v
    use-tag: true

test:
  environment:
    contents:
      packages:
        - jruby-9.4
        - openjdk-11-default-jvm
  pipeline:
    - runs: |
        cat <<EOF > /tmp/test.rb
        require 'jrjackson'

        obj = {:key1 => "value1"}
        puts obj

        result = JrJackson::Json.dump(obj)
        puts result

        puts JrJackson::Json.parse(result)
        EOF

        jruby /tmp/test.rb
