package:
  name: ruff
  version: 0.3.0
  epoch: 0
  description: An extremely fast Python linter, written in Rust.
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - rust

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/astral-sh/ruff
      tag: v${{package.version}}
      expected-commit: b53118ed0016ac37233d3dadbcea9ed3ac1f538e

  - runs: |
      cargo build --release
      mkdir -p ${{targets.destdir}}/usr/bin
      mv target/release/ruff ${{targets.destdir}}/usr/bin/

  - uses: strip

subpackages:
  - name: ruff-python-formatter
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          ls target/release/
          mv target/release/ruff_python_formatter ${{targets.subpkgdir}}/usr/bin/

update:
  enabled: true
  github:
    identifier: astral-sh/ruff
    strip-prefix: v
