package:
  name: skaffold
  version: 2.10.1
  epoch: 0
  description: Easy and Repeatable Kubernetes Development
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
      - make

pipeline:
  - uses: git-checkout
    with:
      expected-commit: df0264229733d654ae0f43466e760dae936b12e7
      repository: https://github.com/GoogleContainerTools/skaffold
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: github.com/cloudflare/circl@v1.3.7 github.com/docker/docker@v24.0.7 github.com/sigstore/cosign/v2@v2.2.1
      replaces: go.opentelemetry.io/otel/sdk/metric=go.opentelemetry.io/otel/sdk/metric@v0.36.0 go.opentelemetry.io/otel/metric=go.opentelemetry.io/otel/metric@v0.36.0 github.com/buildpacks/lifecycle=github.com/buildpacks/lifecycle@v0.17.0 go.opentelemetry.io/otel=go.opentelemetry.io/otel@v1.15.1 go.opentelemetry.io/otel/exporters/stdout/stdoutmetric=go.opentelemetry.io/otel/exporters/stdout/stdoutmetric@v0.36.0 go.opentelemetry.io/otel/sdk=go.opentelemetry.io/otel/sdk@v1.14.0

  - runs: |
      make
      install -m755 -D ./out/skaffold "${{targets.destdir}}"/usr/bin/skaffold

  - uses: strip

update:
  enabled: true
  github:
    identifier: GoogleContainerTools/skaffold
    strip-prefix: v
    tag-filter: v
