package:
  name: skalibs
  version: 2.12.0.1
  epoch: 0
  description: "set of general-purpose C programming libraries for skarnet.org software"
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: ISC
  dependencies:
    runtime:
environment:
  contents:
    packages:
      - wolfi-baselayout
      - busybox
      - ca-certificates-bundle
      - build-base
pipeline:
  - uses: fetch
    with:
      uri: https://skarnet.org/software/skalibs/skalibs-${{package.version}}.tar.gz
      expected-sha256: 3e228f72f18d88c17f6c4e0a66881d6d3779427b7e7e889f3142b6f26da30285
  - name: Configure
    runs: |
      ./configure \
        --enable-shared \
        --enable-static \
        --libdir=/usr/lib
  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip
subpackages:
  - name: "skalibs-dev"
    description: "skalibs development headers"
    pipeline:
      - uses: split/dev
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib/skalibs
          mv "${{targets.destdir}}"/usr/lib/skalibs/sysdeps "${{targets.subpkgdir}}"/usr/lib/skalibs/
