package:
  name: sqlite
  version: 3.40.0
  epoch: 0
  description: "C library which implements an SQL database engine"
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: blessing
  dependencies:
    runtime:
environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/bootstrap/stage3
    keyring:
      - https://packages.wolfi.dev/bootstrap/stage3/wolfi-signing.rsa.pub
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - readline
pipeline:
  - uses: fetch
    with:
      uri: https://www.sqlite.org/2022/sqlite-autoconf-3390400.tar.gz
      expected-sha256: f31d445b48e67e284cf206717cc170ab63cbe4fd7f79a82793b772285e78fdbb
  - name: Configure
    runs: |
      _amalgamation="-DSQLITE_ENABLE_FTS4 \
        -DSQLITE_ENABLE_FTS3_PARENTHESIS \
        -DSQLITE_ENABLE_FTS3 \
        -DSQLITE_ENABLE_FTS5 \
        -DSQLITE_ENABLE_COLUMN_METADATA \
        -DSQLITE_SECURE_DELETE \
        -DSQLITE_ENABLE_UNLOCK_NOTIFY \
        -DSQLITE_ENABLE_RTREE \
        -DSQLITE_ENABLE_GEOPOLY \
        -DSQLITE_USE_URI \
        -DSQLITE_ENABLE_DBSTAT_VTAB \
        -DSQLITE_MAX_VARIABLE_NUMBER=250000"
      export CFLAGS="$CFLAGS $_amalgamation"

      ./configure \
         --host=${{host.triplet.gnu}} \
         --target=${{host.triplet.gnu}} \
         --prefix=/usr \
         --enable-threadsafe \
         --enable-readline \
         --enable-static \
         --enable-dynamic-extensions \
         --enable-fts3

      sed -i 's|^hardcode_libdir_flag_spec=.*|hardcode_libdir_flag_spec=""|g' libtool
      sed -i 's|^runpath_var=LD_RUN_PATH|runpath_var=DIE_RPATH_DIE|g' libtool

      make -j$(nproc) V=1
  - uses: autoconf/make-install
  - uses: strip
subpackages:
  - name: "sqlite-dev"
    description: "sqlite headers"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - sqlite
  - name: "sqlite-doc"
    description: "sqlite documentation"
    pipeline:
      - uses: split/manpages
