package:
  name: sqlpad
  version: 7.4.1 # when updating check the patch below as it contains dependency version updates which may downgrade if upstream upgrades them
  epoch: 1
  description: Web-based SQL editor. Legacy project in maintenance mode.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - nodejs-18 # currently needs node 18, to check in the future see, https://github.com/sqlpad/sqlpad/blob/master/.nvmrc
      - yarn

environment:
  contents:
    packages:
      - build-base
      - busybox
      - nodejs-18
      - python3
      - yarn

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/sqlpad/sqlpad
      expected-commit: 5929bbb5ca78e187952673f454a84aabe80e304a
      tag: v${{package.version}}

  - uses: patch
    with:
      patches: server-package-json.patch

  - uses: patch
    with:
      patches: build-sh.patch

  - runs: |
      ./scripts/build.sh
      mkdir -p ${{targets.destdir}}/usr/bin
      mv server ${{targets.destdir}}/usr/bin/sqlpad-server

  - uses: strip

subpackages:
  - name: "${{package.name}}-compat"
    description: "Compatibility package to place binaries in the location expected by upstream"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/app
          ln -s /usr/bin/sqlpad-server ${{targets.subpkgdir}}/usr/app

update:
  enabled: true
  github:
    identifier: sqlpad/sqlpad
    strip-prefix: v
