package:
  name: swig
  version: 4.2.1
  epoch: 0
  description: A compiler that makes it easy to integrate C and C++ code with scripting languages
  copyright:
    - license: GPL-3.0-only

environment:
  contents:
    packages:
      - autoconf
      - automake
      - bison
      - build-base
      - busybox
      - ca-certificates-bundle
      - guile
      - pcre2-dev
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: fa045354e2d048b2cddc69579e4256245d4676894858fcf0bab2290ecf59b7d8
      uri: https://downloads.sourceforge.net/project/swig/swig/swig-${{package.version}}/swig-${{package.version}}.tar.gz

  - uses: autoconf/configure
    with:
      opts: |
        --host=${{host.triplet.gnu}} \
        --build=${{host.triplet.gnu}} \
        --with-python3=/usr/bin/python3

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 4919
