package:
  name: tcl
  version: 8.6.14
  epoch: 0
  description: The Tcl scripting language
  copyright:
    - license: TCL

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - sqlite-dev
      - tzdata
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: 5880225babf7954c58d4fb0f5cf6279104ce1cd6aa9b71e9a6322540e1c4de66
      uri: https://downloads.sourceforge.net/project/tcl/Tcl/${{package.version}}/tcl${{package.version}}-src.tar.gz

  - uses: patch
    with:
      patches: include_stdint.patch

  - uses: autoconf/configure
    with:
      dir: unix
      opts: |
        --host=${{host.triplet.gnu}} \
        --build=${{host.triplet.gnu}} \
        --prefix=/usr \
        --sysconfdir=/etc \
        --mandir=/usr/share/man \
        --localstatedir=/var \
        --with-system-sqlite \
        --enable-64bit

  - uses: autoconf/make
    with:
      dir: unix

  - runs: |
      cd unix
      # export LD_LIBRARY_PATH="$_builddir"
      make INSTALL_ROOT=${{targets.destdir}} install install-private-headers

      export TCL_VERSION=${{package.version}}

      ln -sf tclsh${TCL_VERSION%.*} ${{targets.destdir}}/usr/bin/tclsh
      install -Dm644 ../license.terms ${{targets.destdir}}/usr/share/licenses/tcl/LICENSE
      chmod u+w ${{targets.destdir}}/usr/lib/libtcl${TCL_VERSION%.*}.so

  - uses: strip

subpackages:
  - name: tcl-doc
    pipeline:
      - uses: split/manpages
    description: tcl manpages

  - name: tcl-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - tcl
        - tzdata
    description: tcl dev

update:
  enabled: true
  release-monitor:
    identifier: 4941
