package:
  name: telegraf-1.31
  version: 1.31.3
  epoch: 0
  description: Telegraf is an agent for collecting, processing, aggregating, and writing metric
  copyright:
    - license: MIT
  dependencies:
    provides:
      - telegraf=${{package.full-version}}

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - gnutar
      - go

pipeline:
  - uses: git-checkout
    with:
      tag: v${{package.version}}
      expected-commit: ecf94b120d812e798a092b1fc0181b699aa063d5
      repository: https://github.com/influxdata/telegraf

  - runs: |
      make package include_packages="linux_${{build.goarch}}.tar.gz"

  - runs: |
      tar -xf build/dist/telegraf-${{package.version}}*.tar.gz
      mkdir -p ${{targets.destdir}}/etc/
      mv telegraf-${{package.version}}/etc/* ${{targets.destdir}}/etc/

      mkdir -p ${{targets.destdir}}/usr/
      mv telegraf-${{package.version}}/usr/* ${{targets.destdir}}/usr

      mkdir -p ${{targets.destdir}}/var
      mv telegraf-${{package.version}}/var/* ${{targets.destdir}}/var

  - uses: strip

update:
  enabled: true
  github:
    identifier: influxdata/telegraf
    strip-prefix: v
    tag-filter: v1.31.
    use-tag: true
