package:
  name: terragrunt
  version: 0.55.10
  epoch: 0
  description: Thin wrapper for Terraform providing extra tools
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - terraform

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: fetch
    with:
      expected-sha256: fbf14cb884031de1d0a122da2e5e096aaa97ce4417b7f21d87377e6a3b23701f
      uri: https://github.com/gruntwork-io/terragrunt/archive/refs/tags/v${{package.version}}.tar.gz

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.17.0

  - runs: |
      go build -v -o bin/terragrunt -ldflags "-s -w -X  github.com/gruntwork-io/go-commons/version.Version=v${{package.version}}"
      install -Dm755 bin/terragrunt "${{targets.destdir}}"/usr/bin/terragrunt

  - uses: strip

update:
  enabled: true
  github:
    identifier: gruntwork-io/terragrunt
    strip-prefix: v
    use-tag: true
    tag-filter: v
