package:
  name: texinfo
  version: 7.0
  epoch: 0
  description: "GNU documentation tool"
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: GPL-3.0-or-later
  dependencies:
    runtime:
      - perl
environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/bootstrap/stage3
    keyring:
      - https://packages.wolfi.dev/bootstrap/stage3/wolfi-signing.rsa.pub
    packages:
      - wolfi-baselayout
      - busybox
      - ca-certificates-bundle
      - build-base
      - ncurses
      - perl
      - xz
pipeline:
  - uses: fetch
    with:
      uri: https://ftp.gnu.org/gnu/texinfo/texinfo-${{package.version}}.tar.xz
      expected-sha256: 20744b82531ce7a04d8cee34b07143ad59777612c3695d5855f29fba40fbe3e0
  - name: 'Configure texinfo'
    runs: |
      ./configure \
        --prefix=/usr \
        --libdir=/lib \
        --sysconfdir=/etc \
        --datadir=/usr/share \
        --mandir=/usr/share/man \
        --infodir=/usr/share/info \
        --host=${{host.triplet.gnu}} \
        --target=${{host.triplet.gnu}}
  - runs: |
      make -j$(nproc) V=1
  - uses: autoconf/make-install
  - runs: |
      rm -f "${{targets.destdir}}"/usr/share/info/dir
  - uses: strip
