package:
  name: trivy
  version: 0.49.1
  epoch: 2
  description: Simple and comprehensive vulnerability scanner for containers
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 6ccc0a554b07b05fd049f882a1825a0e1e0aabe1
      repository: https://github.com/aquasecurity/trivy
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: helm.sh/helm/v3@v3.14.2

  - runs: |
      CGO_ENABLED=0 go build \
        -ldflags "-w -X=main.version=${{package.version}}" \
        -o "${{targets.destdir}}/usr/bin/trivy" ./cmd/trivy

  - uses: strip

update:
  enabled: true
  github:
    identifier: aquasecurity/trivy
    strip-prefix: v
