package:
  name: vite
  version: 5.1.4
  epoch: 0
  description: Vite (French word for "quick", pronounced /vit/, like "veet") is a build tool that aims to provide a faster and leaner development experience for modern web projects.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - nodejs

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - nodejs

pipeline:
  - name: npm install
    runs: |
      npm install -g ${{package.name}}@${{package.version}} -prefix ${{targets.destdir}}/usr

update:
  enabled: true
  ignore-regex-patterns:
    - beta
    - plugin
    - create
  github:
    identifier: vitejs/vite
    strip-prefix: v
