package:
  name: wasker
  version: 0.1.1
  epoch: 1
  description: "Wasm compiler for running Wasm on your favorite kernel"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - libxml2-dev
      - llvm-tools
      - llvm15
      - llvm15-dev
      - rust-1.72 # wasker requires llvm15 rust after this version has a dep on llvm
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/Mewz-project/Wasker
      tag: v${{package.version}}
      expected-commit: 5947507d2529fb33af75b61aa6b824d3a46480d0

  - runs: |
      cargo build --release

  - runs: |
      mkdir -p "${{targets.destdir}}"/usr/bin/
      mv target/release/wasker "${{targets.destdir}}"/usr/bin/

  - uses: strip

update:
  enabled: true
  github:
    identifier: Mewz-project/Wasker
    strip-prefix: v
