package:
  name: wasm-tools
  version: 1.201.0
  epoch: 0
  description: "Low level tooling for WebAssembly in Rust"
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - libLLVM-15
      - rust
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/bytecodealliance/wasm-tools
      tag: v${{package.version}}
      expected-commit: 90161a9b5fbfeaa40e9b4ba2339d7cd1bd52deff

  - name: Configure and build
    runs: |
      cargo build --release -vv
      mkdir -p ${{targets.destdir}}/usr/bin/
      mv target/release/wasm-tools ${{targets.destdir}}/usr/bin/

  - uses: strip

update:
  enabled: true
  github:
    identifier: bytecodealliance/wasm-tools
    strip-prefix: v
    tag-filter: v
