package:
  name: wit-bindgen
  version: 0.19.1
  epoch: 0
  description: "A language binding generator for WebAssembly interface types"
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - libLLVM-15
      - rust
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/bytecodealliance/wit-bindgen
      tag: v${{package.version}}
      expected-commit: e0319e9cf138c71743e425c95adba394b7469778

  - name: Configure and build
    runs: |
      cargo build --release -vv
      mkdir -p ${{targets.destdir}}/usr/bin/
      mv target/release/wit-bindgen ${{targets.destdir}}/usr/bin/

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - wit-bindgen-cli-*
  github:
    identifier: bytecodealliance/wit-bindgen
    strip-prefix: v
