package:
  name: xz
  version: 5.6.0
  epoch: 0
  description: "Library and CLI tools for XZ and LZMA compressed files"
  copyright:
    - license: GPL-3.0-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - wolfi-baselayout

pipeline:
  - uses: fetch # use fetch instead of git-checkout else there is a circular dependency with git
    with:
      uri: https://github.com/tukaani-project/xz/releases/download/v${{package.version}}/xz-${{package.version}}.tar.gz
      expected-sha256: 0f5c81f14171b74fcc9777d302304d964e63ffc2d7b634ef023a7249d9b5d875

  - name: Configure
    runs: |
      ./configure \
         --host=${{host.triplet.gnu}} \
         --target=${{host.triplet.gnu}} \
         --prefix=/usr \
         --datadir=/usr/share

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "xz-dev"
    description: "xz headers"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - xz

  - name: "xz-doc"
    description: "xz documentation"
    pipeline:
      - uses: split/manpages

update:
  enabled: true
  github:
    identifier: tukaani-project/xz
    strip-prefix: v
