package:
  name: yq
  version: 4.42.1
  epoch: 0
  description: "yq is a portable command-line YAML, JSON, XML, CSV and properties processor"
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/mikefarah/yq
      tag: v${{package.version}}
      expected-commit: 9adde1ac14bb283b8955d2b0d567bcaf3c69e639

  - uses: go/build
    with:
      packages: .
      output: yq

  - runs: |
      ${{targets.destdir}}/usr/bin/yq --version | grep "version v${{package.version}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: mikefarah/yq
    strip-prefix: v
