package:
  name: zarf
  version: 0.32.4
  epoch: 0
  description: DevSecOps for Air Gap & Limited-Connection Systems.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - busybox
      - ca-certificates-bundle
      - go
      - nodejs

pipeline:
  - uses: git-checkout
    with:
      expected-commit: f6b83e1c272a22ffd1815b7d38fb6c5f0f1003f9
      repository: https://github.com/defenseunicorns/zarf
      tag: v${{package.version}}

  - uses: go/build
    with:
      ldflags: -s -w -X 'github.com/defenseunicorns/zarf/src/config.CLIVersion=v${{package.version}}'
      output: zarf
      packages: .

  - uses: strip

update:
  enabled: true
  github:
    identifier: defenseunicorns/zarf
    strip-prefix: v
