package:
  name: zot
  version: 2.0.1
  epoch: 5
  description: A production-ready vendor-neutral OCI-native container image registry (purely based on OCI Distribution Specification)
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - curl
      - go-1.21

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 9def35f3b8b38f5a438146a09087edcec00537c7
      repository: https://github.com/project-zot/zot
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.17.0 github.com/containerd/containerd@v1.7.11 github.com/go-git/go-git/v5@v5.11.0 github.com/cloudflare/circl@v1.3.7 github.com/moby/buildkit@v0.12.5 github.com/opencontainers/runc@v1.1.12 github.com/docker/docker@v25.0.1+incompatible helm.sh/helm/v3@v3.14.2
      replaces: oras.land/oras-go=oras.land/oras-go@v1.2.5 github.com/secure-systems-lab/go-securesystemslib=github.com/secure-systems-lab/go-securesystemslib@v0.7.0 helm.sh/helm/v3=helm.sh/helm/v3@v3.14.2 github.com/containerd/containerd=github.com/containerd/containerd@v1.7.11

  - runs: |
      GOARCH=$(go env GOARCH)

      make -o modcheck OS=linux ARCH=${GOARCH} modtidy binary
      install -m755 -D ./bin/zot-linux-${GOARCH} "${{targets.destdir}}"/usr/bin/zot

      make -o modcheck OS=linux ARCH=${GOARCH} modtidy cli
      install -m755 -D ./bin/zli-linux-${GOARCH} "${{targets.destdir}}"/usr/bin/zli

  - uses: strip

update:
  enabled: true
  github:
    identifier: project-zot/zot
    strip-prefix: v
