issuer: https://accounts.google.com

# staging: bot-epoch-bot@staging-enforce-cd1e.iam.gserviceaccount.com
# prod: TODO
subject_pattern: "(101928776192101947682|TODO)"

permissions:
  contents: read
  checks: write
