name: Wolfictl Check Updates

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - gh-readonly-queue/main/**

jobs:
  lint:
    name: Wolfictl Check Updates
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Get changed files
      id: files
      uses: tj-actions/changed-files@716b1e13042866565e00e85fd4ec490e186c4a2f #tj-actions/changed-files@v41.0.1
      with:
        separator: ' '
        files: "*.yaml"
        files_ignore: ".yam.yaml"

    - name: Check
      id: check
      uses: wolfi-dev/actions/wolfictl-check-updates@main
      if: ${{ steps.files.outputs.all_changed_files != '' }}
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        changed_files: ${{ steps.files.outputs.all_changed_files }}
